//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.07 at 10:08:36 PM CEST 
//


package org.artemis.configuration.jaxb2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *             Complex type element to configure an address.
 *          
 * 
 * <p>Java class for addressSettingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addressSettingType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="dead-letter-address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="auto-create-dead-letter-resources" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="dead-letter-queue-prefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dead-letter-queue-suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="expiry-address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="auto-create-expiry-resources" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="expiry-queue-prefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="expiry-queue-suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="expiry-delay" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="min-expiry-delay" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="max-expiry-delay" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="redelivery-delay" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="redelivery-delay-multiplier" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="redelivery-collision-avoidance-factor" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="max-redelivery-delay" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="max-delivery-attempts" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="max-size-bytes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="max-size-messages" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="page-limit-bytes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="page-limit-messages" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="max-size-bytes-reject-threshold" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="page-size-bytes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="page-max-cache-size" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="max-read-page-messages" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="prefetch-page-messages" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="max-read-page-bytes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="prefetch-page-bytes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="address-full-policy" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="DROP"/&gt;
 *               &lt;enumeration value="FAIL"/&gt;
 *               &lt;enumeration value="PAGE"/&gt;
 *               &lt;enumeration value="BLOCK"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="page-full-policy" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="DROP"/&gt;
 *               &lt;enumeration value="FAIL"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="message-counter-history-day-limit" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="last-value-queue" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="default-last-value-queue" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="default-last-value-key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="default-non-destructive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="default-exclusive-queue" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="default-group-rebalance" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="default-group-rebalance-pause-dispatch" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="default-group-buckets" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="default-group-first-key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="default-consumers-before-dispatch" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="default-delay-before-dispatch" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="redistribution-delay" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="send-to-dla-on-no-route" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="slow-consumer-threshold" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="slow-consumer-threshold-measurement-unit" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="MESSAGES_PER_SECOND"/&gt;
 *               &lt;enumeration value="MESSAGES_PER_MINUTE"/&gt;
 *               &lt;enumeration value="MESSAGES_PER_HOUR"/&gt;
 *               &lt;enumeration value="MESSAGES_PER_DAY"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="slow-consumer-policy" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="KILL"/&gt;
 *               &lt;enumeration value="NOTIFY"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="slow-consumer-check-period" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="auto-create-jms-queues" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="auto-delete-jms-queues" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="auto-create-jms-topics" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="auto-delete-jms-topics" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="auto-create-queues" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="auto-delete-queues" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="auto-delete-created-queues" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="auto-delete-queues-delay" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="auto-delete-queues-message-count" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="auto-delete-queues-skip-usage-check" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="config-delete-queues" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="OFF"/&gt;
 *               &lt;enumeration value="FORCE"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="auto-create-addresses" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="auto-delete-addresses" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="auto-delete-addresses-delay" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="auto-delete-addresses-skip-usage-check" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="config-delete-addresses" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="OFF"/&gt;
 *               &lt;enumeration value="FORCE"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="config-delete-diverts" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="OFF"/&gt;
 *               &lt;enumeration value="FORCE"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="management-browse-page-size" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="management-message-attribute-size-limit" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="default-purge-on-no-consumers" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="default-max-consumers" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="default-queue-routing-type" type="{urn:activemq:core}routing-type" minOccurs="0"/&gt;
 *         &lt;element name="default-address-routing-type" type="{urn:activemq:core}routing-type" minOccurs="0"/&gt;
 *         &lt;element name="default-consumer-window-size" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="default-ring-size" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="retroactive-message-count" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="enable-metrics" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="enable-ingress-timestamp" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="id-cache-size" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="initial-queue-buffer-size" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *       &lt;attGroup ref="{http://www.w3.org/XML/1998/namespace}specialAttrs"/&gt;
 *       &lt;attribute name="match" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addressSettingType", propOrder = {

})
public class AddressSettingType {

    @XmlElement(name = "dead-letter-address")
    protected String deadLetterAddress;
    @XmlElement(name = "auto-create-dead-letter-resources", defaultValue = "false")
    protected Boolean autoCreateDeadLetterResources;
    @XmlElement(name = "dead-letter-queue-prefix", defaultValue = "DLQ.")
    protected String deadLetterQueuePrefix;
    @XmlElement(name = "dead-letter-queue-suffix", defaultValue = "")
    protected String deadLetterQueueSuffix;
    @XmlElement(name = "expiry-address")
    protected String expiryAddress;
    @XmlElement(name = "auto-create-expiry-resources", defaultValue = "false")
    protected Boolean autoCreateExpiryResources;
    @XmlElement(name = "expiry-queue-prefix", defaultValue = "EXP.")
    protected String expiryQueuePrefix;
    @XmlElement(name = "expiry-queue-suffix", defaultValue = "")
    protected String expiryQueueSuffix;
    @XmlElement(name = "expiry-delay", defaultValue = "-1")
    protected Long expiryDelay;
    @XmlElement(name = "min-expiry-delay", defaultValue = "-1")
    protected Long minExpiryDelay;
    @XmlElement(name = "max-expiry-delay", defaultValue = "-1")
    protected Long maxExpiryDelay;
    @XmlElement(name = "redelivery-delay", defaultValue = "0")
    protected Long redeliveryDelay;
    @XmlElement(name = "redelivery-delay-multiplier")
    protected Double redeliveryDelayMultiplier;
    @XmlElement(name = "redelivery-collision-avoidance-factor")
    protected Double redeliveryCollisionAvoidanceFactor;
    @XmlElement(name = "max-redelivery-delay")
    protected Long maxRedeliveryDelay;
    @XmlElement(name = "max-delivery-attempts", defaultValue = "10")
    protected Integer maxDeliveryAttempts;
    @XmlElement(name = "max-size-bytes", defaultValue = "-1")
    protected String maxSizeBytes;
    @XmlElement(name = "max-size-messages", defaultValue = "-1")
    protected Long maxSizeMessages;
    @XmlElement(name = "page-limit-bytes")
    protected String pageLimitBytes;
    @XmlElement(name = "page-limit-messages")
    protected Long pageLimitMessages;
    @XmlElement(name = "max-size-bytes-reject-threshold", defaultValue = "-1")
    protected Long maxSizeBytesRejectThreshold;
    @XmlElement(name = "page-size-bytes", defaultValue = "10485760")
    protected String pageSizeBytes;
    @XmlElement(name = "page-max-cache-size", defaultValue = "5")
    protected Integer pageMaxCacheSize;
    @XmlElement(name = "max-read-page-messages", defaultValue = "-1")
    protected Integer maxReadPageMessages;
    @XmlElement(name = "prefetch-page-messages", defaultValue = "-1")
    protected Integer prefetchPageMessages;
    @XmlElement(name = "max-read-page-bytes", defaultValue = "20M")
    protected String maxReadPageBytes;
    @XmlElement(name = "prefetch-page-bytes", defaultValue = "-1")
    protected String prefetchPageBytes;
    @XmlElement(name = "address-full-policy")
    protected String addressFullPolicy;
    @XmlElement(name = "page-full-policy")
    protected String pageFullPolicy;
    @XmlElement(name = "message-counter-history-day-limit", defaultValue = "0")
    protected Integer messageCounterHistoryDayLimit;
    @XmlElement(name = "last-value-queue", defaultValue = "false")
    protected Boolean lastValueQueue;
    @XmlElement(name = "default-last-value-queue", defaultValue = "false")
    protected Boolean defaultLastValueQueue;
    @XmlElement(name = "default-last-value-key")
    protected String defaultLastValueKey;
    @XmlElement(name = "default-non-destructive", defaultValue = "false")
    protected Boolean defaultNonDestructive;
    @XmlElement(name = "default-exclusive-queue", defaultValue = "false")
    protected Boolean defaultExclusiveQueue;
    @XmlElement(name = "default-group-rebalance", defaultValue = "false")
    protected Boolean defaultGroupRebalance;
    @XmlElement(name = "default-group-rebalance-pause-dispatch", defaultValue = "false")
    protected Boolean defaultGroupRebalancePauseDispatch;
    @XmlElement(name = "default-group-buckets", defaultValue = "-1")
    protected Integer defaultGroupBuckets;
    @XmlElement(name = "default-group-first-key")
    protected String defaultGroupFirstKey;
    @XmlElement(name = "default-consumers-before-dispatch", defaultValue = "0")
    protected Integer defaultConsumersBeforeDispatch;
    @XmlElement(name = "default-delay-before-dispatch", defaultValue = "-1")
    protected Long defaultDelayBeforeDispatch;
    @XmlElement(name = "redistribution-delay", defaultValue = "-1")
    protected Long redistributionDelay;
    @XmlElement(name = "send-to-dla-on-no-route")
    protected Boolean sendToDlaOnNoRoute;
    @XmlElement(name = "slow-consumer-threshold")
    protected Long slowConsumerThreshold;
    @XmlElement(name = "slow-consumer-threshold-measurement-unit")
    protected String slowConsumerThresholdMeasurementUnit;
    @XmlElement(name = "slow-consumer-policy", defaultValue = "NOTIFY")
    protected String slowConsumerPolicy;
    @XmlElement(name = "slow-consumer-check-period")
    protected Long slowConsumerCheckPeriod;
    @XmlElement(name = "auto-create-jms-queues", defaultValue = "true")
    protected Boolean autoCreateJmsQueues;
    @XmlElement(name = "auto-delete-jms-queues", defaultValue = "true")
    protected Boolean autoDeleteJmsQueues;
    @XmlElement(name = "auto-create-jms-topics", defaultValue = "true")
    protected Boolean autoCreateJmsTopics;
    @XmlElement(name = "auto-delete-jms-topics", defaultValue = "true")
    protected Boolean autoDeleteJmsTopics;
    @XmlElement(name = "auto-create-queues", defaultValue = "true")
    protected Boolean autoCreateQueues;
    @XmlElement(name = "auto-delete-queues", defaultValue = "true")
    protected Boolean autoDeleteQueues;
    @XmlElement(name = "auto-delete-created-queues", defaultValue = "false")
    protected Boolean autoDeleteCreatedQueues;
    @XmlElement(name = "auto-delete-queues-delay", defaultValue = "0")
    protected Long autoDeleteQueuesDelay;
    @XmlElement(name = "auto-delete-queues-message-count", defaultValue = "0")
    protected Long autoDeleteQueuesMessageCount;
    @XmlElement(name = "auto-delete-queues-skip-usage-check", defaultValue = "false")
    protected Boolean autoDeleteQueuesSkipUsageCheck;
    @XmlElement(name = "config-delete-queues", defaultValue = "OFF")
    protected String configDeleteQueues;
    @XmlElement(name = "auto-create-addresses", defaultValue = "true")
    protected Boolean autoCreateAddresses;
    @XmlElement(name = "auto-delete-addresses", defaultValue = "true")
    protected Boolean autoDeleteAddresses;
    @XmlElement(name = "auto-delete-addresses-delay", defaultValue = "0")
    protected Long autoDeleteAddressesDelay;
    @XmlElement(name = "auto-delete-addresses-skip-usage-check", defaultValue = "false")
    protected Boolean autoDeleteAddressesSkipUsageCheck;
    @XmlElement(name = "config-delete-addresses", defaultValue = "OFF")
    protected String configDeleteAddresses;
    @XmlElement(name = "config-delete-diverts", defaultValue = "OFF")
    protected String configDeleteDiverts;
    @XmlElement(name = "management-browse-page-size", defaultValue = "200")
    protected Integer managementBrowsePageSize;
    @XmlElement(name = "management-message-attribute-size-limit", defaultValue = "256")
    protected Integer managementMessageAttributeSizeLimit;
    @XmlElement(name = "default-purge-on-no-consumers", defaultValue = "false")
    protected Boolean defaultPurgeOnNoConsumers;
    @XmlElement(name = "default-max-consumers", defaultValue = "-1")
    protected Integer defaultMaxConsumers;
    @XmlElement(name = "default-queue-routing-type", defaultValue = "MULTICAST")
    @XmlSchemaType(name = "string")
    protected RoutingType defaultQueueRoutingType;
    @XmlElement(name = "default-address-routing-type", defaultValue = "MULTICAST")
    @XmlSchemaType(name = "string")
    protected RoutingType defaultAddressRoutingType;
    @XmlElement(name = "default-consumer-window-size", defaultValue = "-1")
    protected Integer defaultConsumerWindowSize;
    @XmlElement(name = "default-ring-size", defaultValue = "-1")
    protected Long defaultRingSize;
    @XmlElement(name = "retroactive-message-count", defaultValue = "0")
    protected Long retroactiveMessageCount;
    @XmlElement(name = "enable-metrics", defaultValue = "true")
    protected Boolean enableMetrics;
    @XmlElement(name = "enable-ingress-timestamp", defaultValue = "false")
    protected Boolean enableIngressTimestamp;
    @XmlElement(name = "id-cache-size", defaultValue = "20000")
    protected Integer idCacheSize;
    @XmlElement(name = "initial-queue-buffer-size", defaultValue = "8192")
    protected Integer initialQueueBufferSize;
    @XmlAttribute(name = "match", required = true)
    protected String match;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;

    /**
     * Gets the value of the deadLetterAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeadLetterAddress() {
        return deadLetterAddress;
    }

    /**
     * Sets the value of the deadLetterAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeadLetterAddress(String value) {
        this.deadLetterAddress = value;
    }

    /**
     * Gets the value of the autoCreateDeadLetterResources property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoCreateDeadLetterResources() {
        return autoCreateDeadLetterResources;
    }

    /**
     * Sets the value of the autoCreateDeadLetterResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoCreateDeadLetterResources(Boolean value) {
        this.autoCreateDeadLetterResources = value;
    }

    /**
     * Gets the value of the deadLetterQueuePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeadLetterQueuePrefix() {
        return deadLetterQueuePrefix;
    }

    /**
     * Sets the value of the deadLetterQueuePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeadLetterQueuePrefix(String value) {
        this.deadLetterQueuePrefix = value;
    }

    /**
     * Gets the value of the deadLetterQueueSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeadLetterQueueSuffix() {
        return deadLetterQueueSuffix;
    }

    /**
     * Sets the value of the deadLetterQueueSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeadLetterQueueSuffix(String value) {
        this.deadLetterQueueSuffix = value;
    }

    /**
     * Gets the value of the expiryAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiryAddress() {
        return expiryAddress;
    }

    /**
     * Sets the value of the expiryAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiryAddress(String value) {
        this.expiryAddress = value;
    }

    /**
     * Gets the value of the autoCreateExpiryResources property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoCreateExpiryResources() {
        return autoCreateExpiryResources;
    }

    /**
     * Sets the value of the autoCreateExpiryResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoCreateExpiryResources(Boolean value) {
        this.autoCreateExpiryResources = value;
    }

    /**
     * Gets the value of the expiryQueuePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiryQueuePrefix() {
        return expiryQueuePrefix;
    }

    /**
     * Sets the value of the expiryQueuePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiryQueuePrefix(String value) {
        this.expiryQueuePrefix = value;
    }

    /**
     * Gets the value of the expiryQueueSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiryQueueSuffix() {
        return expiryQueueSuffix;
    }

    /**
     * Sets the value of the expiryQueueSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiryQueueSuffix(String value) {
        this.expiryQueueSuffix = value;
    }

    /**
     * Gets the value of the expiryDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getExpiryDelay() {
        return expiryDelay;
    }

    /**
     * Sets the value of the expiryDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setExpiryDelay(Long value) {
        this.expiryDelay = value;
    }

    /**
     * Gets the value of the minExpiryDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMinExpiryDelay() {
        return minExpiryDelay;
    }

    /**
     * Sets the value of the minExpiryDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMinExpiryDelay(Long value) {
        this.minExpiryDelay = value;
    }

    /**
     * Gets the value of the maxExpiryDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxExpiryDelay() {
        return maxExpiryDelay;
    }

    /**
     * Sets the value of the maxExpiryDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxExpiryDelay(Long value) {
        this.maxExpiryDelay = value;
    }

    /**
     * Gets the value of the redeliveryDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRedeliveryDelay() {
        return redeliveryDelay;
    }

    /**
     * Sets the value of the redeliveryDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRedeliveryDelay(Long value) {
        this.redeliveryDelay = value;
    }

    /**
     * Gets the value of the redeliveryDelayMultiplier property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRedeliveryDelayMultiplier() {
        return redeliveryDelayMultiplier;
    }

    /**
     * Sets the value of the redeliveryDelayMultiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRedeliveryDelayMultiplier(Double value) {
        this.redeliveryDelayMultiplier = value;
    }

    /**
     * Gets the value of the redeliveryCollisionAvoidanceFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRedeliveryCollisionAvoidanceFactor() {
        return redeliveryCollisionAvoidanceFactor;
    }

    /**
     * Sets the value of the redeliveryCollisionAvoidanceFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRedeliveryCollisionAvoidanceFactor(Double value) {
        this.redeliveryCollisionAvoidanceFactor = value;
    }

    /**
     * Gets the value of the maxRedeliveryDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxRedeliveryDelay() {
        return maxRedeliveryDelay;
    }

    /**
     * Sets the value of the maxRedeliveryDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxRedeliveryDelay(Long value) {
        this.maxRedeliveryDelay = value;
    }

    /**
     * Gets the value of the maxDeliveryAttempts property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxDeliveryAttempts() {
        return maxDeliveryAttempts;
    }

    /**
     * Sets the value of the maxDeliveryAttempts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxDeliveryAttempts(Integer value) {
        this.maxDeliveryAttempts = value;
    }

    /**
     * Gets the value of the maxSizeBytes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxSizeBytes() {
        return maxSizeBytes;
    }

    /**
     * Sets the value of the maxSizeBytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxSizeBytes(String value) {
        this.maxSizeBytes = value;
    }

    /**
     * Gets the value of the maxSizeMessages property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxSizeMessages() {
        return maxSizeMessages;
    }

    /**
     * Sets the value of the maxSizeMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxSizeMessages(Long value) {
        this.maxSizeMessages = value;
    }

    /**
     * Gets the value of the pageLimitBytes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageLimitBytes() {
        return pageLimitBytes;
    }

    /**
     * Sets the value of the pageLimitBytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageLimitBytes(String value) {
        this.pageLimitBytes = value;
    }

    /**
     * Gets the value of the pageLimitMessages property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPageLimitMessages() {
        return pageLimitMessages;
    }

    /**
     * Sets the value of the pageLimitMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPageLimitMessages(Long value) {
        this.pageLimitMessages = value;
    }

    /**
     * Gets the value of the maxSizeBytesRejectThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxSizeBytesRejectThreshold() {
        return maxSizeBytesRejectThreshold;
    }

    /**
     * Sets the value of the maxSizeBytesRejectThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxSizeBytesRejectThreshold(Long value) {
        this.maxSizeBytesRejectThreshold = value;
    }

    /**
     * Gets the value of the pageSizeBytes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageSizeBytes() {
        return pageSizeBytes;
    }

    /**
     * Sets the value of the pageSizeBytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageSizeBytes(String value) {
        this.pageSizeBytes = value;
    }

    /**
     * Gets the value of the pageMaxCacheSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPageMaxCacheSize() {
        return pageMaxCacheSize;
    }

    /**
     * Sets the value of the pageMaxCacheSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPageMaxCacheSize(Integer value) {
        this.pageMaxCacheSize = value;
    }

    /**
     * Gets the value of the maxReadPageMessages property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxReadPageMessages() {
        return maxReadPageMessages;
    }

    /**
     * Sets the value of the maxReadPageMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxReadPageMessages(Integer value) {
        this.maxReadPageMessages = value;
    }

    /**
     * Gets the value of the prefetchPageMessages property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPrefetchPageMessages() {
        return prefetchPageMessages;
    }

    /**
     * Sets the value of the prefetchPageMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPrefetchPageMessages(Integer value) {
        this.prefetchPageMessages = value;
    }

    /**
     * Gets the value of the maxReadPageBytes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxReadPageBytes() {
        return maxReadPageBytes;
    }

    /**
     * Sets the value of the maxReadPageBytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxReadPageBytes(String value) {
        this.maxReadPageBytes = value;
    }

    /**
     * Gets the value of the prefetchPageBytes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefetchPageBytes() {
        return prefetchPageBytes;
    }

    /**
     * Sets the value of the prefetchPageBytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefetchPageBytes(String value) {
        this.prefetchPageBytes = value;
    }

    /**
     * Gets the value of the addressFullPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressFullPolicy() {
        return addressFullPolicy;
    }

    /**
     * Sets the value of the addressFullPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressFullPolicy(String value) {
        this.addressFullPolicy = value;
    }

    /**
     * Gets the value of the pageFullPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageFullPolicy() {
        return pageFullPolicy;
    }

    /**
     * Sets the value of the pageFullPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageFullPolicy(String value) {
        this.pageFullPolicy = value;
    }

    /**
     * Gets the value of the messageCounterHistoryDayLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMessageCounterHistoryDayLimit() {
        return messageCounterHistoryDayLimit;
    }

    /**
     * Sets the value of the messageCounterHistoryDayLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMessageCounterHistoryDayLimit(Integer value) {
        this.messageCounterHistoryDayLimit = value;
    }

    /**
     * Gets the value of the lastValueQueue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLastValueQueue() {
        return lastValueQueue;
    }

    /**
     * Sets the value of the lastValueQueue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLastValueQueue(Boolean value) {
        this.lastValueQueue = value;
    }

    /**
     * Gets the value of the defaultLastValueQueue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDefaultLastValueQueue() {
        return defaultLastValueQueue;
    }

    /**
     * Sets the value of the defaultLastValueQueue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDefaultLastValueQueue(Boolean value) {
        this.defaultLastValueQueue = value;
    }

    /**
     * Gets the value of the defaultLastValueKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultLastValueKey() {
        return defaultLastValueKey;
    }

    /**
     * Sets the value of the defaultLastValueKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultLastValueKey(String value) {
        this.defaultLastValueKey = value;
    }

    /**
     * Gets the value of the defaultNonDestructive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDefaultNonDestructive() {
        return defaultNonDestructive;
    }

    /**
     * Sets the value of the defaultNonDestructive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDefaultNonDestructive(Boolean value) {
        this.defaultNonDestructive = value;
    }

    /**
     * Gets the value of the defaultExclusiveQueue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDefaultExclusiveQueue() {
        return defaultExclusiveQueue;
    }

    /**
     * Sets the value of the defaultExclusiveQueue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDefaultExclusiveQueue(Boolean value) {
        this.defaultExclusiveQueue = value;
    }

    /**
     * Gets the value of the defaultGroupRebalance property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDefaultGroupRebalance() {
        return defaultGroupRebalance;
    }

    /**
     * Sets the value of the defaultGroupRebalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDefaultGroupRebalance(Boolean value) {
        this.defaultGroupRebalance = value;
    }

    /**
     * Gets the value of the defaultGroupRebalancePauseDispatch property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDefaultGroupRebalancePauseDispatch() {
        return defaultGroupRebalancePauseDispatch;
    }

    /**
     * Sets the value of the defaultGroupRebalancePauseDispatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDefaultGroupRebalancePauseDispatch(Boolean value) {
        this.defaultGroupRebalancePauseDispatch = value;
    }

    /**
     * Gets the value of the defaultGroupBuckets property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDefaultGroupBuckets() {
        return defaultGroupBuckets;
    }

    /**
     * Sets the value of the defaultGroupBuckets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDefaultGroupBuckets(Integer value) {
        this.defaultGroupBuckets = value;
    }

    /**
     * Gets the value of the defaultGroupFirstKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultGroupFirstKey() {
        return defaultGroupFirstKey;
    }

    /**
     * Sets the value of the defaultGroupFirstKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultGroupFirstKey(String value) {
        this.defaultGroupFirstKey = value;
    }

    /**
     * Gets the value of the defaultConsumersBeforeDispatch property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDefaultConsumersBeforeDispatch() {
        return defaultConsumersBeforeDispatch;
    }

    /**
     * Sets the value of the defaultConsumersBeforeDispatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDefaultConsumersBeforeDispatch(Integer value) {
        this.defaultConsumersBeforeDispatch = value;
    }

    /**
     * Gets the value of the defaultDelayBeforeDispatch property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDefaultDelayBeforeDispatch() {
        return defaultDelayBeforeDispatch;
    }

    /**
     * Sets the value of the defaultDelayBeforeDispatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDefaultDelayBeforeDispatch(Long value) {
        this.defaultDelayBeforeDispatch = value;
    }

    /**
     * Gets the value of the redistributionDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRedistributionDelay() {
        return redistributionDelay;
    }

    /**
     * Sets the value of the redistributionDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRedistributionDelay(Long value) {
        this.redistributionDelay = value;
    }

    /**
     * Gets the value of the sendToDlaOnNoRoute property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSendToDlaOnNoRoute() {
        return sendToDlaOnNoRoute;
    }

    /**
     * Sets the value of the sendToDlaOnNoRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSendToDlaOnNoRoute(Boolean value) {
        this.sendToDlaOnNoRoute = value;
    }

    /**
     * Gets the value of the slowConsumerThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSlowConsumerThreshold() {
        return slowConsumerThreshold;
    }

    /**
     * Sets the value of the slowConsumerThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSlowConsumerThreshold(Long value) {
        this.slowConsumerThreshold = value;
    }

    /**
     * Gets the value of the slowConsumerThresholdMeasurementUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlowConsumerThresholdMeasurementUnit() {
        return slowConsumerThresholdMeasurementUnit;
    }

    /**
     * Sets the value of the slowConsumerThresholdMeasurementUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlowConsumerThresholdMeasurementUnit(String value) {
        this.slowConsumerThresholdMeasurementUnit = value;
    }

    /**
     * Gets the value of the slowConsumerPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlowConsumerPolicy() {
        return slowConsumerPolicy;
    }

    /**
     * Sets the value of the slowConsumerPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlowConsumerPolicy(String value) {
        this.slowConsumerPolicy = value;
    }

    /**
     * Gets the value of the slowConsumerCheckPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSlowConsumerCheckPeriod() {
        return slowConsumerCheckPeriod;
    }

    /**
     * Sets the value of the slowConsumerCheckPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSlowConsumerCheckPeriod(Long value) {
        this.slowConsumerCheckPeriod = value;
    }

    /**
     * Gets the value of the autoCreateJmsQueues property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoCreateJmsQueues() {
        return autoCreateJmsQueues;
    }

    /**
     * Sets the value of the autoCreateJmsQueues property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoCreateJmsQueues(Boolean value) {
        this.autoCreateJmsQueues = value;
    }

    /**
     * Gets the value of the autoDeleteJmsQueues property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoDeleteJmsQueues() {
        return autoDeleteJmsQueues;
    }

    /**
     * Sets the value of the autoDeleteJmsQueues property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoDeleteJmsQueues(Boolean value) {
        this.autoDeleteJmsQueues = value;
    }

    /**
     * Gets the value of the autoCreateJmsTopics property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoCreateJmsTopics() {
        return autoCreateJmsTopics;
    }

    /**
     * Sets the value of the autoCreateJmsTopics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoCreateJmsTopics(Boolean value) {
        this.autoCreateJmsTopics = value;
    }

    /**
     * Gets the value of the autoDeleteJmsTopics property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoDeleteJmsTopics() {
        return autoDeleteJmsTopics;
    }

    /**
     * Sets the value of the autoDeleteJmsTopics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoDeleteJmsTopics(Boolean value) {
        this.autoDeleteJmsTopics = value;
    }

    /**
     * Gets the value of the autoCreateQueues property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoCreateQueues() {
        return autoCreateQueues;
    }

    /**
     * Sets the value of the autoCreateQueues property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoCreateQueues(Boolean value) {
        this.autoCreateQueues = value;
    }

    /**
     * Gets the value of the autoDeleteQueues property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoDeleteQueues() {
        return autoDeleteQueues;
    }

    /**
     * Sets the value of the autoDeleteQueues property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoDeleteQueues(Boolean value) {
        this.autoDeleteQueues = value;
    }

    /**
     * Gets the value of the autoDeleteCreatedQueues property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoDeleteCreatedQueues() {
        return autoDeleteCreatedQueues;
    }

    /**
     * Sets the value of the autoDeleteCreatedQueues property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoDeleteCreatedQueues(Boolean value) {
        this.autoDeleteCreatedQueues = value;
    }

    /**
     * Gets the value of the autoDeleteQueuesDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAutoDeleteQueuesDelay() {
        return autoDeleteQueuesDelay;
    }

    /**
     * Sets the value of the autoDeleteQueuesDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAutoDeleteQueuesDelay(Long value) {
        this.autoDeleteQueuesDelay = value;
    }

    /**
     * Gets the value of the autoDeleteQueuesMessageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAutoDeleteQueuesMessageCount() {
        return autoDeleteQueuesMessageCount;
    }

    /**
     * Sets the value of the autoDeleteQueuesMessageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAutoDeleteQueuesMessageCount(Long value) {
        this.autoDeleteQueuesMessageCount = value;
    }

    /**
     * Gets the value of the autoDeleteQueuesSkipUsageCheck property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoDeleteQueuesSkipUsageCheck() {
        return autoDeleteQueuesSkipUsageCheck;
    }

    /**
     * Sets the value of the autoDeleteQueuesSkipUsageCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoDeleteQueuesSkipUsageCheck(Boolean value) {
        this.autoDeleteQueuesSkipUsageCheck = value;
    }

    /**
     * Gets the value of the configDeleteQueues property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigDeleteQueues() {
        return configDeleteQueues;
    }

    /**
     * Sets the value of the configDeleteQueues property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigDeleteQueues(String value) {
        this.configDeleteQueues = value;
    }

    /**
     * Gets the value of the autoCreateAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoCreateAddresses() {
        return autoCreateAddresses;
    }

    /**
     * Sets the value of the autoCreateAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoCreateAddresses(Boolean value) {
        this.autoCreateAddresses = value;
    }

    /**
     * Gets the value of the autoDeleteAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoDeleteAddresses() {
        return autoDeleteAddresses;
    }

    /**
     * Sets the value of the autoDeleteAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoDeleteAddresses(Boolean value) {
        this.autoDeleteAddresses = value;
    }

    /**
     * Gets the value of the autoDeleteAddressesDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAutoDeleteAddressesDelay() {
        return autoDeleteAddressesDelay;
    }

    /**
     * Sets the value of the autoDeleteAddressesDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAutoDeleteAddressesDelay(Long value) {
        this.autoDeleteAddressesDelay = value;
    }

    /**
     * Gets the value of the autoDeleteAddressesSkipUsageCheck property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoDeleteAddressesSkipUsageCheck() {
        return autoDeleteAddressesSkipUsageCheck;
    }

    /**
     * Sets the value of the autoDeleteAddressesSkipUsageCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoDeleteAddressesSkipUsageCheck(Boolean value) {
        this.autoDeleteAddressesSkipUsageCheck = value;
    }

    /**
     * Gets the value of the configDeleteAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigDeleteAddresses() {
        return configDeleteAddresses;
    }

    /**
     * Sets the value of the configDeleteAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigDeleteAddresses(String value) {
        this.configDeleteAddresses = value;
    }

    /**
     * Gets the value of the configDeleteDiverts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigDeleteDiverts() {
        return configDeleteDiverts;
    }

    /**
     * Sets the value of the configDeleteDiverts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigDeleteDiverts(String value) {
        this.configDeleteDiverts = value;
    }

    /**
     * Gets the value of the managementBrowsePageSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getManagementBrowsePageSize() {
        return managementBrowsePageSize;
    }

    /**
     * Sets the value of the managementBrowsePageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setManagementBrowsePageSize(Integer value) {
        this.managementBrowsePageSize = value;
    }

    /**
     * Gets the value of the managementMessageAttributeSizeLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getManagementMessageAttributeSizeLimit() {
        return managementMessageAttributeSizeLimit;
    }

    /**
     * Sets the value of the managementMessageAttributeSizeLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setManagementMessageAttributeSizeLimit(Integer value) {
        this.managementMessageAttributeSizeLimit = value;
    }

    /**
     * Gets the value of the defaultPurgeOnNoConsumers property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDefaultPurgeOnNoConsumers() {
        return defaultPurgeOnNoConsumers;
    }

    /**
     * Sets the value of the defaultPurgeOnNoConsumers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDefaultPurgeOnNoConsumers(Boolean value) {
        this.defaultPurgeOnNoConsumers = value;
    }

    /**
     * Gets the value of the defaultMaxConsumers property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDefaultMaxConsumers() {
        return defaultMaxConsumers;
    }

    /**
     * Sets the value of the defaultMaxConsumers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDefaultMaxConsumers(Integer value) {
        this.defaultMaxConsumers = value;
    }

    /**
     * Gets the value of the defaultQueueRoutingType property.
     * 
     * @return
     *     possible object is
     *     {@link RoutingType }
     *     
     */
    public RoutingType getDefaultQueueRoutingType() {
        return defaultQueueRoutingType;
    }

    /**
     * Sets the value of the defaultQueueRoutingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoutingType }
     *     
     */
    public void setDefaultQueueRoutingType(RoutingType value) {
        this.defaultQueueRoutingType = value;
    }

    /**
     * Gets the value of the defaultAddressRoutingType property.
     * 
     * @return
     *     possible object is
     *     {@link RoutingType }
     *     
     */
    public RoutingType getDefaultAddressRoutingType() {
        return defaultAddressRoutingType;
    }

    /**
     * Sets the value of the defaultAddressRoutingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoutingType }
     *     
     */
    public void setDefaultAddressRoutingType(RoutingType value) {
        this.defaultAddressRoutingType = value;
    }

    /**
     * Gets the value of the defaultConsumerWindowSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDefaultConsumerWindowSize() {
        return defaultConsumerWindowSize;
    }

    /**
     * Sets the value of the defaultConsumerWindowSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDefaultConsumerWindowSize(Integer value) {
        this.defaultConsumerWindowSize = value;
    }

    /**
     * Gets the value of the defaultRingSize property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDefaultRingSize() {
        return defaultRingSize;
    }

    /**
     * Sets the value of the defaultRingSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDefaultRingSize(Long value) {
        this.defaultRingSize = value;
    }

    /**
     * Gets the value of the retroactiveMessageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRetroactiveMessageCount() {
        return retroactiveMessageCount;
    }

    /**
     * Sets the value of the retroactiveMessageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRetroactiveMessageCount(Long value) {
        this.retroactiveMessageCount = value;
    }

    /**
     * Gets the value of the enableMetrics property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableMetrics() {
        return enableMetrics;
    }

    /**
     * Sets the value of the enableMetrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableMetrics(Boolean value) {
        this.enableMetrics = value;
    }

    /**
     * Gets the value of the enableIngressTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableIngressTimestamp() {
        return enableIngressTimestamp;
    }

    /**
     * Sets the value of the enableIngressTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableIngressTimestamp(Boolean value) {
        this.enableIngressTimestamp = value;
    }

    /**
     * Gets the value of the idCacheSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdCacheSize() {
        return idCacheSize;
    }

    /**
     * Sets the value of the idCacheSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdCacheSize(Integer value) {
        this.idCacheSize = value;
    }

    /**
     * Gets the value of the initialQueueBufferSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInitialQueueBufferSize() {
        return initialQueueBufferSize;
    }

    /**
     * Sets the value of the initialQueueBufferSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInitialQueueBufferSize(Integer value) {
        this.initialQueueBufferSize = value;
    }

    /**
     * Gets the value of the match property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatch() {
        return match;
    }

    /**
     * Sets the value of the match property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatch(String value) {
        this.match = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

}
