//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.07 at 10:08:36 PM CEST 
//


package org.artemis.configuration.jaxb2;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *             This create a federation between this broker and the remote that is being
 *             connected to, federation can occur in either direction over this connection
 *             depending on the address and queue policy configurations.
 *          
 * 
 * <p>Java class for amqp-federation-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="amqp-federation-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded"&gt;
 *         &lt;choice maxOccurs="unbounded"&gt;
 *           &lt;element name="local-queue-policy" type="{urn:activemq:core}amqpFederationQueuePolicyType"/&gt;
 *           &lt;element name="local-address-policy" type="{urn:activemq:core}amqpFederationAddressPolicyType"/&gt;
 *           &lt;element name="remote-queue-policy" type="{urn:activemq:core}amqpFederationQueuePolicyType"/&gt;
 *           &lt;element name="remote-address-policy" type="{urn:activemq:core}amqpFederationAddressPolicyType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{urn:activemq:core}property" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "amqp-federation-type", propOrder = {
    "localQueuePolicyOrLocalAddressPolicyOrRemoteQueuePolicy"
})
public class AmqpFederationType {

    @XmlElementRefs({
        @XmlElementRef(name = "local-queue-policy", namespace = "urn:activemq:core", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "local-address-policy", namespace = "urn:activemq:core", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "remote-queue-policy", namespace = "urn:activemq:core", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "remote-address-policy", namespace = "urn:activemq:core", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "property", namespace = "urn:activemq:core", type = Property.class, required = false)
    })
    protected List<Object> localQueuePolicyOrLocalAddressPolicyOrRemoteQueuePolicy;

    /**
     * Gets the value of the localQueuePolicyOrLocalAddressPolicyOrRemoteQueuePolicy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the localQueuePolicyOrLocalAddressPolicyOrRemoteQueuePolicy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalQueuePolicyOrLocalAddressPolicyOrRemoteQueuePolicy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link AmqpFederationQueuePolicyType }{@code >}
     * {@link JAXBElement }{@code <}{@link AmqpFederationAddressPolicyType }{@code >}
     * {@link JAXBElement }{@code <}{@link AmqpFederationQueuePolicyType }{@code >}
     * {@link JAXBElement }{@code <}{@link AmqpFederationAddressPolicyType }{@code >}
     * {@link Property }
     * 
     * 
     */
    public List<Object> getLocalQueuePolicyOrLocalAddressPolicyOrRemoteQueuePolicy() {
        if (localQueuePolicyOrLocalAddressPolicyOrRemoteQueuePolicy == null) {
            localQueuePolicyOrLocalAddressPolicyOrRemoteQueuePolicy = new ArrayList<Object>();
        }
        return this.localQueuePolicyOrLocalAddressPolicyOrRemoteQueuePolicy;
    }

}
