//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.07 at 10:08:36 PM CEST 
//


package org.artemis.configuration.jaxb2;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for bridgeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bridgeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="queue-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="forwarding-address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ha" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:activemq:core}filter" minOccurs="0"/&gt;
 *         &lt;element name="transformer-class-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="transformer" type="{urn:activemq:core}transformerType" minOccurs="0"/&gt;
 *         &lt;element name="min-large-message-size" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="check-period" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="connection-ttl" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="retry-interval" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="retry-interval-multiplier" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="max-retry-interval" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="initial-connect-attempts" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="reconnect-attempts" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="failover-on-server-shutdown" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="use-duplicate-detection" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="confirmation-window-size" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="producer-window-size" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="reconnect-attempts-same-node" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="routing-type" type="{urn:activemq:core}component-routing-type" minOccurs="0"/&gt;
 *         &lt;element name="concurrency" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="pending-ack-timeout" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="client-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:activemq:core}discovery-type"/&gt;
 *       &lt;/all&gt;
 *       &lt;attGroup ref="{http://www.w3.org/XML/1998/namespace}specialAttrs"/&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bridgeType", propOrder = {

})
public class BridgeType {

    @XmlElement(name = "queue-name", required = true)
    protected String queueName;
    @XmlElement(name = "forwarding-address")
    protected String forwardingAddress;
    @XmlElement(defaultValue = "false")
    protected Boolean ha;
    protected Filter filter;
    @XmlElement(name = "transformer-class-name")
    protected String transformerClassName;
    protected TransformerType transformer;
    @XmlElement(name = "min-large-message-size", defaultValue = "102400")
    protected String minLargeMessageSize;
    @XmlElement(name = "check-period", defaultValue = "30000")
    protected Long checkPeriod;
    @XmlElement(name = "connection-ttl", defaultValue = "60000")
    protected Long connectionTtl;
    @XmlElement(name = "retry-interval", defaultValue = "2000")
    protected Long retryInterval;
    @XmlElement(name = "retry-interval-multiplier", defaultValue = "1")
    protected Double retryIntervalMultiplier;
    @XmlElement(name = "max-retry-interval", defaultValue = "2000")
    protected Long maxRetryInterval;
    @XmlElement(name = "initial-connect-attempts", defaultValue = "-1")
    protected Integer initialConnectAttempts;
    @XmlElement(name = "reconnect-attempts", defaultValue = "-1")
    protected Integer reconnectAttempts;
    @XmlElement(name = "failover-on-server-shutdown", defaultValue = "false")
    protected Boolean failoverOnServerShutdown;
    @XmlElement(name = "use-duplicate-detection", defaultValue = "true")
    protected Boolean useDuplicateDetection;
    @XmlElement(name = "confirmation-window-size", defaultValue = "1048576")
    protected String confirmationWindowSize;
    @XmlElement(name = "producer-window-size", defaultValue = "1048576")
    protected String producerWindowSize;
    protected String user;
    protected String password;
    @XmlElement(name = "reconnect-attempts-same-node", defaultValue = "10")
    protected Integer reconnectAttemptsSameNode;
    @XmlElement(name = "routing-type", defaultValue = "PASS")
    @XmlSchemaType(name = "string")
    protected ComponentRoutingType routingType;
    @XmlElement(defaultValue = "1")
    protected Integer concurrency;
    @XmlElement(name = "pending-ack-timeout", defaultValue = "60000")
    protected Long pendingAckTimeout;
    @XmlElement(name = "client-id")
    protected String clientId;
    @XmlElementRef(name = "discovery-type", namespace = "urn:activemq:core", type = JAXBElement.class)
    protected JAXBElement<?> discoveryType;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String name;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;

    /**
     * Gets the value of the queueName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueueName() {
        return queueName;
    }

    /**
     * Sets the value of the queueName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueueName(String value) {
        this.queueName = value;
    }

    /**
     * Gets the value of the forwardingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForwardingAddress() {
        return forwardingAddress;
    }

    /**
     * Sets the value of the forwardingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForwardingAddress(String value) {
        this.forwardingAddress = value;
    }

    /**
     * Gets the value of the ha property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHa() {
        return ha;
    }

    /**
     * Sets the value of the ha property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHa(Boolean value) {
        this.ha = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link Filter }
     *     
     */
    public Filter getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Filter }
     *     
     */
    public void setFilter(Filter value) {
        this.filter = value;
    }

    /**
     * Gets the value of the transformerClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransformerClassName() {
        return transformerClassName;
    }

    /**
     * Sets the value of the transformerClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransformerClassName(String value) {
        this.transformerClassName = value;
    }

    /**
     * Gets the value of the transformer property.
     * 
     * @return
     *     possible object is
     *     {@link TransformerType }
     *     
     */
    public TransformerType getTransformer() {
        return transformer;
    }

    /**
     * Sets the value of the transformer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransformerType }
     *     
     */
    public void setTransformer(TransformerType value) {
        this.transformer = value;
    }

    /**
     * Gets the value of the minLargeMessageSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinLargeMessageSize() {
        return minLargeMessageSize;
    }

    /**
     * Sets the value of the minLargeMessageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinLargeMessageSize(String value) {
        this.minLargeMessageSize = value;
    }

    /**
     * Gets the value of the checkPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCheckPeriod() {
        return checkPeriod;
    }

    /**
     * Sets the value of the checkPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCheckPeriod(Long value) {
        this.checkPeriod = value;
    }

    /**
     * Gets the value of the connectionTtl property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getConnectionTtl() {
        return connectionTtl;
    }

    /**
     * Sets the value of the connectionTtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setConnectionTtl(Long value) {
        this.connectionTtl = value;
    }

    /**
     * Gets the value of the retryInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRetryInterval() {
        return retryInterval;
    }

    /**
     * Sets the value of the retryInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRetryInterval(Long value) {
        this.retryInterval = value;
    }

    /**
     * Gets the value of the retryIntervalMultiplier property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRetryIntervalMultiplier() {
        return retryIntervalMultiplier;
    }

    /**
     * Sets the value of the retryIntervalMultiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRetryIntervalMultiplier(Double value) {
        this.retryIntervalMultiplier = value;
    }

    /**
     * Gets the value of the maxRetryInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxRetryInterval() {
        return maxRetryInterval;
    }

    /**
     * Sets the value of the maxRetryInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxRetryInterval(Long value) {
        this.maxRetryInterval = value;
    }

    /**
     * Gets the value of the initialConnectAttempts property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInitialConnectAttempts() {
        return initialConnectAttempts;
    }

    /**
     * Sets the value of the initialConnectAttempts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInitialConnectAttempts(Integer value) {
        this.initialConnectAttempts = value;
    }

    /**
     * Gets the value of the reconnectAttempts property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReconnectAttempts() {
        return reconnectAttempts;
    }

    /**
     * Sets the value of the reconnectAttempts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReconnectAttempts(Integer value) {
        this.reconnectAttempts = value;
    }

    /**
     * Gets the value of the failoverOnServerShutdown property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFailoverOnServerShutdown() {
        return failoverOnServerShutdown;
    }

    /**
     * Sets the value of the failoverOnServerShutdown property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFailoverOnServerShutdown(Boolean value) {
        this.failoverOnServerShutdown = value;
    }

    /**
     * Gets the value of the useDuplicateDetection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseDuplicateDetection() {
        return useDuplicateDetection;
    }

    /**
     * Sets the value of the useDuplicateDetection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseDuplicateDetection(Boolean value) {
        this.useDuplicateDetection = value;
    }

    /**
     * Gets the value of the confirmationWindowSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfirmationWindowSize() {
        return confirmationWindowSize;
    }

    /**
     * Sets the value of the confirmationWindowSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfirmationWindowSize(String value) {
        this.confirmationWindowSize = value;
    }

    /**
     * Gets the value of the producerWindowSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducerWindowSize() {
        return producerWindowSize;
    }

    /**
     * Sets the value of the producerWindowSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducerWindowSize(String value) {
        this.producerWindowSize = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the reconnectAttemptsSameNode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReconnectAttemptsSameNode() {
        return reconnectAttemptsSameNode;
    }

    /**
     * Sets the value of the reconnectAttemptsSameNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReconnectAttemptsSameNode(Integer value) {
        this.reconnectAttemptsSameNode = value;
    }

    /**
     * Gets the value of the routingType property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentRoutingType }
     *     
     */
    public ComponentRoutingType getRoutingType() {
        return routingType;
    }

    /**
     * Sets the value of the routingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentRoutingType }
     *     
     */
    public void setRoutingType(ComponentRoutingType value) {
        this.routingType = value;
    }

    /**
     * Gets the value of the concurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getConcurrency() {
        return concurrency;
    }

    /**
     * Sets the value of the concurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setConcurrency(Integer value) {
        this.concurrency = value;
    }

    /**
     * Gets the value of the pendingAckTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPendingAckTimeout() {
        return pendingAckTimeout;
    }

    /**
     * Sets the value of the pendingAckTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPendingAckTimeout(Long value) {
        this.pendingAckTimeout = value;
    }

    /**
     * Gets the value of the clientId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientId(String value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the discoveryType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DiscoveryGroupRef }{@code >}
     *     {@link JAXBElement }{@code <}{@link StaticConnectors }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public JAXBElement<?> getDiscoveryType() {
        return discoveryType;
    }

    /**
     * Sets the value of the discoveryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DiscoveryGroupRef }{@code >}
     *     {@link JAXBElement }{@code <}{@link StaticConnectors }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public void setDiscoveryType(JAXBElement<?> value) {
        this.discoveryType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

}
