//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.07 at 10:08:36 PM CEST 
//


package org.artemis.configuration.jaxb2;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for cluster-connectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cluster-connectionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="connector-ref" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="check-period" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="connection-ttl" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="min-large-message-size" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="call-timeout" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="retry-interval" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="retry-interval-multiplier" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="max-retry-interval" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="initial-connect-attempts" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="reconnect-attempts" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="use-duplicate-detection" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="forward-when-no-consumers" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="message-load-balancing" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="OFF"/&gt;
 *               &lt;enumeration value="STRICT"/&gt;
 *               &lt;enumeration value="ON_DEMAND"/&gt;
 *               &lt;enumeration value="OFF_WITH_REDISTRIBUTION"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="max-hops" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="confirmation-window-size" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="producer-window-size" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="call-failover-timeout" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="notification-interval" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="notification-attempts" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="scale-down-connector" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="client-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:activemq:core}discovery-type" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *       &lt;attGroup ref="{http://www.w3.org/XML/1998/namespace}specialAttrs"/&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *       &lt;attribute name="uri" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cluster-connectionType", propOrder = {

})
public class ClusterConnectionType {

    protected String address;
    @XmlElement(name = "connector-ref", required = true)
    protected String connectorRef;
    @XmlElement(name = "check-period", defaultValue = "30000")
    protected Long checkPeriod;
    @XmlElement(name = "connection-ttl", defaultValue = "60000")
    protected Long connectionTtl;
    @XmlElement(name = "min-large-message-size")
    protected String minLargeMessageSize;
    @XmlElement(name = "call-timeout", defaultValue = "30000")
    protected Long callTimeout;
    @XmlElement(name = "retry-interval", defaultValue = "500")
    protected Long retryInterval;
    @XmlElement(name = "retry-interval-multiplier", defaultValue = "1")
    protected Double retryIntervalMultiplier;
    @XmlElement(name = "max-retry-interval", defaultValue = "2000")
    protected Long maxRetryInterval;
    @XmlElement(name = "initial-connect-attempts", defaultValue = "-1")
    protected Integer initialConnectAttempts;
    @XmlElement(name = "reconnect-attempts", defaultValue = "-1")
    protected Integer reconnectAttempts;
    @XmlElement(name = "use-duplicate-detection", defaultValue = "true")
    protected Boolean useDuplicateDetection;
    @XmlElement(name = "forward-when-no-consumers", defaultValue = "false")
    protected Boolean forwardWhenNoConsumers;
    @XmlElement(name = "message-load-balancing", defaultValue = "ON_DEMAND")
    protected String messageLoadBalancing;
    @XmlElement(name = "max-hops", defaultValue = "1")
    protected Integer maxHops;
    @XmlElement(name = "confirmation-window-size", defaultValue = "1048576")
    protected String confirmationWindowSize;
    @XmlElement(name = "producer-window-size", defaultValue = "1048576")
    protected String producerWindowSize;
    @XmlElement(name = "call-failover-timeout", defaultValue = "-1")
    protected Long callFailoverTimeout;
    @XmlElement(name = "notification-interval", defaultValue = "1000")
    protected Long notificationInterval;
    @XmlElement(name = "notification-attempts", defaultValue = "2")
    protected Integer notificationAttempts;
    @XmlElement(name = "scale-down-connector")
    protected String scaleDownConnector;
    @XmlElement(name = "client-id")
    protected String clientId;
    @XmlElementRef(name = "discovery-type", namespace = "urn:activemq:core", type = JAXBElement.class, required = false)
    protected JAXBElement<?> discoveryType;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String name;
    @XmlAttribute(name = "uri")
    protected String uri;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the connectorRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectorRef() {
        return connectorRef;
    }

    /**
     * Sets the value of the connectorRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectorRef(String value) {
        this.connectorRef = value;
    }

    /**
     * Gets the value of the checkPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCheckPeriod() {
        return checkPeriod;
    }

    /**
     * Sets the value of the checkPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCheckPeriod(Long value) {
        this.checkPeriod = value;
    }

    /**
     * Gets the value of the connectionTtl property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getConnectionTtl() {
        return connectionTtl;
    }

    /**
     * Sets the value of the connectionTtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setConnectionTtl(Long value) {
        this.connectionTtl = value;
    }

    /**
     * Gets the value of the minLargeMessageSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinLargeMessageSize() {
        return minLargeMessageSize;
    }

    /**
     * Sets the value of the minLargeMessageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinLargeMessageSize(String value) {
        this.minLargeMessageSize = value;
    }

    /**
     * Gets the value of the callTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCallTimeout() {
        return callTimeout;
    }

    /**
     * Sets the value of the callTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCallTimeout(Long value) {
        this.callTimeout = value;
    }

    /**
     * Gets the value of the retryInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRetryInterval() {
        return retryInterval;
    }

    /**
     * Sets the value of the retryInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRetryInterval(Long value) {
        this.retryInterval = value;
    }

    /**
     * Gets the value of the retryIntervalMultiplier property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRetryIntervalMultiplier() {
        return retryIntervalMultiplier;
    }

    /**
     * Sets the value of the retryIntervalMultiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRetryIntervalMultiplier(Double value) {
        this.retryIntervalMultiplier = value;
    }

    /**
     * Gets the value of the maxRetryInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxRetryInterval() {
        return maxRetryInterval;
    }

    /**
     * Sets the value of the maxRetryInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxRetryInterval(Long value) {
        this.maxRetryInterval = value;
    }

    /**
     * Gets the value of the initialConnectAttempts property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInitialConnectAttempts() {
        return initialConnectAttempts;
    }

    /**
     * Sets the value of the initialConnectAttempts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInitialConnectAttempts(Integer value) {
        this.initialConnectAttempts = value;
    }

    /**
     * Gets the value of the reconnectAttempts property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReconnectAttempts() {
        return reconnectAttempts;
    }

    /**
     * Sets the value of the reconnectAttempts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReconnectAttempts(Integer value) {
        this.reconnectAttempts = value;
    }

    /**
     * Gets the value of the useDuplicateDetection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseDuplicateDetection() {
        return useDuplicateDetection;
    }

    /**
     * Sets the value of the useDuplicateDetection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseDuplicateDetection(Boolean value) {
        this.useDuplicateDetection = value;
    }

    /**
     * Gets the value of the forwardWhenNoConsumers property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isForwardWhenNoConsumers() {
        return forwardWhenNoConsumers;
    }

    /**
     * Sets the value of the forwardWhenNoConsumers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setForwardWhenNoConsumers(Boolean value) {
        this.forwardWhenNoConsumers = value;
    }

    /**
     * Gets the value of the messageLoadBalancing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageLoadBalancing() {
        return messageLoadBalancing;
    }

    /**
     * Sets the value of the messageLoadBalancing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageLoadBalancing(String value) {
        this.messageLoadBalancing = value;
    }

    /**
     * Gets the value of the maxHops property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxHops() {
        return maxHops;
    }

    /**
     * Sets the value of the maxHops property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxHops(Integer value) {
        this.maxHops = value;
    }

    /**
     * Gets the value of the confirmationWindowSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfirmationWindowSize() {
        return confirmationWindowSize;
    }

    /**
     * Sets the value of the confirmationWindowSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfirmationWindowSize(String value) {
        this.confirmationWindowSize = value;
    }

    /**
     * Gets the value of the producerWindowSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducerWindowSize() {
        return producerWindowSize;
    }

    /**
     * Sets the value of the producerWindowSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducerWindowSize(String value) {
        this.producerWindowSize = value;
    }

    /**
     * Gets the value of the callFailoverTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCallFailoverTimeout() {
        return callFailoverTimeout;
    }

    /**
     * Sets the value of the callFailoverTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCallFailoverTimeout(Long value) {
        this.callFailoverTimeout = value;
    }

    /**
     * Gets the value of the notificationInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNotificationInterval() {
        return notificationInterval;
    }

    /**
     * Sets the value of the notificationInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNotificationInterval(Long value) {
        this.notificationInterval = value;
    }

    /**
     * Gets the value of the notificationAttempts property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNotificationAttempts() {
        return notificationAttempts;
    }

    /**
     * Sets the value of the notificationAttempts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNotificationAttempts(Integer value) {
        this.notificationAttempts = value;
    }

    /**
     * Gets the value of the scaleDownConnector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScaleDownConnector() {
        return scaleDownConnector;
    }

    /**
     * Sets the value of the scaleDownConnector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScaleDownConnector(String value) {
        this.scaleDownConnector = value;
    }

    /**
     * Gets the value of the clientId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientId(String value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the discoveryType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DiscoveryGroupRef }{@code >}
     *     {@link JAXBElement }{@code <}{@link StaticConnectors }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public JAXBElement<?> getDiscoveryType() {
        return discoveryType;
    }

    /**
     * Sets the value of the discoveryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DiscoveryGroupRef }{@code >}
     *     {@link JAXBElement }{@code <}{@link StaticConnectors }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public void setDiscoveryType(JAXBElement<?> value) {
        this.discoveryType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

}
