//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.07 at 10:08:36 PM CEST 
//


package org.artemis.configuration.jaxb2;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for connectionRouterKeyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="connectionRouterKeyType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CLIENT_ID"/&gt;
 *     &lt;enumeration value="SNI_HOST"/&gt;
 *     &lt;enumeration value="SOURCE_IP"/&gt;
 *     &lt;enumeration value="USER_NAME"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "connectionRouterKeyType")
@XmlEnum
public enum ConnectionRouterKeyType {

    CLIENT_ID,
    SNI_HOST,
    SOURCE_IP,
    USER_NAME;

    public String value() {
        return name();
    }

    public static ConnectionRouterKeyType fromValue(String v) {
        return valueOf(v);
    }

}
