//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.07 at 10:08:36 PM CEST 
//


package org.artemis.configuration.jaxb2;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for databaseStoreType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="databaseStoreType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="jdbc-driver-class-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="jdbc-connection-url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="jdbc-user" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="jdbc-password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="data-source-class-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="data-source-properties" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="data-source-property" type="{urn:activemq:core}propertyType" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="message-table-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bindings-table-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="large-message-table-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="page-store-table-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="node-manager-store-table-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="jdbc-network-timeout" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="jdbc-lock-renew-period" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="jdbc-lock-expiration" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="jdbc-journal-sync-period" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="jdbc-allowed-time-diff" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="jdbc-max-page-size-bytes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *       &lt;attGroup ref="{http://www.w3.org/XML/1998/namespace}specialAttrs"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "databaseStoreType", propOrder = {

})
public class DatabaseStoreType {

    @XmlElement(name = "jdbc-driver-class-name")
    protected String jdbcDriverClassName;
    @XmlElement(name = "jdbc-connection-url")
    protected String jdbcConnectionUrl;
    @XmlElement(name = "jdbc-user")
    protected String jdbcUser;
    @XmlElement(name = "jdbc-password")
    protected String jdbcPassword;
    @XmlElement(name = "data-source-class-name")
    protected String dataSourceClassName;
    @XmlElement(name = "data-source-properties")
    protected DatabaseStoreType.DataSourceProperties dataSourceProperties;
    @XmlElement(name = "message-table-name", required = true)
    protected String messageTableName;
    @XmlElement(name = "bindings-table-name", required = true)
    protected String bindingsTableName;
    @XmlElement(name = "large-message-table-name", required = true)
    protected String largeMessageTableName;
    @XmlElement(name = "page-store-table-name", required = true)
    protected String pageStoreTableName;
    @XmlElement(name = "node-manager-store-table-name")
    protected String nodeManagerStoreTableName;
    @XmlElement(name = "jdbc-network-timeout")
    protected Integer jdbcNetworkTimeout;
    @XmlElement(name = "jdbc-lock-renew-period")
    protected Integer jdbcLockRenewPeriod;
    @XmlElement(name = "jdbc-lock-expiration")
    protected Integer jdbcLockExpiration;
    @XmlElement(name = "jdbc-journal-sync-period")
    protected String jdbcJournalSyncPeriod;
    @XmlElement(name = "jdbc-allowed-time-diff", defaultValue = "250")
    protected Long jdbcAllowedTimeDiff;
    @XmlElement(name = "jdbc-max-page-size-bytes", defaultValue = "102400")
    protected String jdbcMaxPageSizeBytes;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;

    /**
     * Gets the value of the jdbcDriverClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJdbcDriverClassName() {
        return jdbcDriverClassName;
    }

    /**
     * Sets the value of the jdbcDriverClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJdbcDriverClassName(String value) {
        this.jdbcDriverClassName = value;
    }

    /**
     * Gets the value of the jdbcConnectionUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJdbcConnectionUrl() {
        return jdbcConnectionUrl;
    }

    /**
     * Sets the value of the jdbcConnectionUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJdbcConnectionUrl(String value) {
        this.jdbcConnectionUrl = value;
    }

    /**
     * Gets the value of the jdbcUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJdbcUser() {
        return jdbcUser;
    }

    /**
     * Sets the value of the jdbcUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJdbcUser(String value) {
        this.jdbcUser = value;
    }

    /**
     * Gets the value of the jdbcPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJdbcPassword() {
        return jdbcPassword;
    }

    /**
     * Sets the value of the jdbcPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJdbcPassword(String value) {
        this.jdbcPassword = value;
    }

    /**
     * Gets the value of the dataSourceClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSourceClassName() {
        return dataSourceClassName;
    }

    /**
     * Sets the value of the dataSourceClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSourceClassName(String value) {
        this.dataSourceClassName = value;
    }

    /**
     * Gets the value of the dataSourceProperties property.
     * 
     * @return
     *     possible object is
     *     {@link DatabaseStoreType.DataSourceProperties }
     *     
     */
    public DatabaseStoreType.DataSourceProperties getDataSourceProperties() {
        return dataSourceProperties;
    }

    /**
     * Sets the value of the dataSourceProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatabaseStoreType.DataSourceProperties }
     *     
     */
    public void setDataSourceProperties(DatabaseStoreType.DataSourceProperties value) {
        this.dataSourceProperties = value;
    }

    /**
     * Gets the value of the messageTableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageTableName() {
        return messageTableName;
    }

    /**
     * Sets the value of the messageTableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageTableName(String value) {
        this.messageTableName = value;
    }

    /**
     * Gets the value of the bindingsTableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBindingsTableName() {
        return bindingsTableName;
    }

    /**
     * Sets the value of the bindingsTableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBindingsTableName(String value) {
        this.bindingsTableName = value;
    }

    /**
     * Gets the value of the largeMessageTableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLargeMessageTableName() {
        return largeMessageTableName;
    }

    /**
     * Sets the value of the largeMessageTableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLargeMessageTableName(String value) {
        this.largeMessageTableName = value;
    }

    /**
     * Gets the value of the pageStoreTableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageStoreTableName() {
        return pageStoreTableName;
    }

    /**
     * Sets the value of the pageStoreTableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageStoreTableName(String value) {
        this.pageStoreTableName = value;
    }

    /**
     * Gets the value of the nodeManagerStoreTableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeManagerStoreTableName() {
        return nodeManagerStoreTableName;
    }

    /**
     * Sets the value of the nodeManagerStoreTableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeManagerStoreTableName(String value) {
        this.nodeManagerStoreTableName = value;
    }

    /**
     * Gets the value of the jdbcNetworkTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getJdbcNetworkTimeout() {
        return jdbcNetworkTimeout;
    }

    /**
     * Sets the value of the jdbcNetworkTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setJdbcNetworkTimeout(Integer value) {
        this.jdbcNetworkTimeout = value;
    }

    /**
     * Gets the value of the jdbcLockRenewPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getJdbcLockRenewPeriod() {
        return jdbcLockRenewPeriod;
    }

    /**
     * Sets the value of the jdbcLockRenewPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setJdbcLockRenewPeriod(Integer value) {
        this.jdbcLockRenewPeriod = value;
    }

    /**
     * Gets the value of the jdbcLockExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getJdbcLockExpiration() {
        return jdbcLockExpiration;
    }

    /**
     * Sets the value of the jdbcLockExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setJdbcLockExpiration(Integer value) {
        this.jdbcLockExpiration = value;
    }

    /**
     * Gets the value of the jdbcJournalSyncPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJdbcJournalSyncPeriod() {
        return jdbcJournalSyncPeriod;
    }

    /**
     * Sets the value of the jdbcJournalSyncPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJdbcJournalSyncPeriod(String value) {
        this.jdbcJournalSyncPeriod = value;
    }

    /**
     * Gets the value of the jdbcAllowedTimeDiff property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getJdbcAllowedTimeDiff() {
        return jdbcAllowedTimeDiff;
    }

    /**
     * Sets the value of the jdbcAllowedTimeDiff property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setJdbcAllowedTimeDiff(Long value) {
        this.jdbcAllowedTimeDiff = value;
    }

    /**
     * Gets the value of the jdbcMaxPageSizeBytes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJdbcMaxPageSizeBytes() {
        return jdbcMaxPageSizeBytes;
    }

    /**
     * Sets the value of the jdbcMaxPageSizeBytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJdbcMaxPageSizeBytes(String value) {
        this.jdbcMaxPageSizeBytes = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="data-source-property" type="{urn:activemq:core}propertyType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataSourceProperty"
    })
    public static class DataSourceProperties {

        @XmlElement(name = "data-source-property", required = true)
        protected List<PropertyType> dataSourceProperty;

        /**
         * Gets the value of the dataSourceProperty property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the dataSourceProperty property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDataSourceProperty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PropertyType }
         * 
         * 
         */
        public List<PropertyType> getDataSourceProperty() {
            if (dataSourceProperty == null) {
                dataSourceProperty = new ArrayList<PropertyType>();
            }
            return this.dataSourceProperty;
        }

    }

}
