//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.07 at 10:08:36 PM CEST 
//


package org.artemis.configuration.jaxb2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for discoveryGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="discoveryGroupType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="group-address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="group-port" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="jgroups-file" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="jgroups-channel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="refresh-timeout" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:activemq:core}local-bind-address" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:activemq:core}local-bind-port" minOccurs="0"/&gt;
 *         &lt;element name="initial-wait-timeout" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *       &lt;attGroup ref="{http://www.w3.org/XML/1998/namespace}specialAttrs"/&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "discoveryGroupType", propOrder = {

})
public class DiscoveryGroupType {

    @XmlElement(name = "group-address")
    protected String groupAddress;
    @XmlElement(name = "group-port")
    protected Integer groupPort;
    @XmlElement(name = "jgroups-file")
    protected String jgroupsFile;
    @XmlElement(name = "jgroups-channel")
    protected String jgroupsChannel;
    @XmlElement(name = "refresh-timeout", defaultValue = "10000")
    protected Integer refreshTimeout;
    @XmlElement(name = "local-bind-address")
    protected String localBindAddress;
    @XmlElement(name = "local-bind-port", defaultValue = "-1")
    protected Integer localBindPort;
    @XmlElement(name = "initial-wait-timeout", defaultValue = "10000")
    protected Integer initialWaitTimeout;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String name;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;

    /**
     * Gets the value of the groupAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupAddress() {
        return groupAddress;
    }

    /**
     * Sets the value of the groupAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupAddress(String value) {
        this.groupAddress = value;
    }

    /**
     * Gets the value of the groupPort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGroupPort() {
        return groupPort;
    }

    /**
     * Sets the value of the groupPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGroupPort(Integer value) {
        this.groupPort = value;
    }

    /**
     * Gets the value of the jgroupsFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJgroupsFile() {
        return jgroupsFile;
    }

    /**
     * Sets the value of the jgroupsFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJgroupsFile(String value) {
        this.jgroupsFile = value;
    }

    /**
     * Gets the value of the jgroupsChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJgroupsChannel() {
        return jgroupsChannel;
    }

    /**
     * Sets the value of the jgroupsChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJgroupsChannel(String value) {
        this.jgroupsChannel = value;
    }

    /**
     * Gets the value of the refreshTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRefreshTimeout() {
        return refreshTimeout;
    }

    /**
     * Sets the value of the refreshTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRefreshTimeout(Integer value) {
        this.refreshTimeout = value;
    }

    /**
     * Gets the value of the localBindAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalBindAddress() {
        return localBindAddress;
    }

    /**
     * Sets the value of the localBindAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalBindAddress(String value) {
        this.localBindAddress = value;
    }

    /**
     * Gets the value of the localBindPort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLocalBindPort() {
        return localBindPort;
    }

    /**
     * Sets the value of the localBindPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLocalBindPort(Integer value) {
        this.localBindPort = value;
    }

    /**
     * Gets the value of the initialWaitTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInitialWaitTimeout() {
        return initialWaitTimeout;
    }

    /**
     * Sets the value of the initialWaitTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInitialWaitTimeout(Integer value) {
        this.initialWaitTimeout = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

}
