//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.07 at 10:08:36 PM CEST 
//


package org.artemis.configuration.jaxb2;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="jmx-domain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{urn:activemq:jms}queue"/&gt;
 *           &lt;element ref="{urn:activemq:jms}topic"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "jmxDomain",
    "queueOrTopic"
})
@XmlRootElement(name = "jms", namespace = "urn:activemq:jms")
public class Jms {

    @XmlElement(name = "jmx-domain", namespace = "urn:activemq:jms", defaultValue = "org.apache.activemq")
    protected String jmxDomain;
    @XmlElements({
        @XmlElement(name = "queue", namespace = "urn:activemq:jms", type = JmsQueueType.class),
        @XmlElement(name = "topic", namespace = "urn:activemq:jms", type = TopicType.class)
    })
    protected List<Object> queueOrTopic;

    /**
     * Gets the value of the jmxDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmxDomain() {
        return jmxDomain;
    }

    /**
     * Sets the value of the jmxDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmxDomain(String value) {
        this.jmxDomain = value;
    }

    /**
     * Gets the value of the queueOrTopic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the queueOrTopic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQueueOrTopic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JmsQueueType }
     * {@link TopicType }
     * 
     * 
     */
    public List<Object> getQueueOrTopic() {
        if (queueOrTopic == null) {
            queueOrTopic = new ArrayList<Object>();
        }
        return this.queueOrTopic;
    }

}
