//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.10 at 03:47:13 PM CEST 
//


package org.artemis.configuration.jaxb2;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.artemis.configuration.jaxb2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Core_QNAME = new QName("urn:activemq:core", "core");
    private final static QName _LocalBindAddress_QNAME = new QName("urn:activemq:core", "local-bind-address");
    private final static QName _LocalBindPort_QNAME = new QName("urn:activemq:core", "local-bind-port");
    private final static QName _DiscoveryType_QNAME = new QName("urn:activemq:core", "discovery-type");
    private final static QName _StaticConnectors_QNAME = new QName("urn:activemq:core", "static-connectors");
    private final static QName _DiscoveryGroupRef_QNAME = new QName("urn:activemq:core", "discovery-group-ref");
    private final static QName _Store_QNAME = new QName("urn:activemq:core", "store");
    private final static QName _GroupingHandler_QNAME = new QName("urn:activemq:core", "grouping-handler");
    private final static QName _Queue_QNAME = new QName("urn:activemq:jms", "queue");
    private final static QName _Topic_QNAME = new QName("urn:activemq:jms", "topic");
    private final static QName _AmqpFederationTypeLocalQueuePolicy_QNAME = new QName("urn:activemq:core", "local-queue-policy");
    private final static QName _AmqpFederationTypeLocalAddressPolicy_QNAME = new QName("urn:activemq:core", "local-address-policy");
    private final static QName _AmqpFederationTypeRemoteQueuePolicy_QNAME = new QName("urn:activemq:core", "remote-queue-policy");
    private final static QName _AmqpFederationTypeRemoteAddressPolicy_QNAME = new QName("urn:activemq:core", "remote-address-policy");
    private final static QName _ConnectionRouterPoolTypeUsername_QNAME = new QName("urn:activemq:core", "username");
    private final static QName _ConnectionRouterPoolTypePassword_QNAME = new QName("urn:activemq:core", "password");
    private final static QName _ConnectionRouterPoolTypeCheckPeriod_QNAME = new QName("urn:activemq:core", "check-period");
    private final static QName _ConnectionRouterPoolTypeQuorumSize_QNAME = new QName("urn:activemq:core", "quorum-size");
    private final static QName _ConnectionRouterPoolTypeQuorumTimeout_QNAME = new QName("urn:activemq:core", "quorum-timeout");
    private final static QName _ConnectionRouterPoolTypeLocalTargetEnabled_QNAME = new QName("urn:activemq:core", "local-target-enabled");
    private final static QName _ConnectionRouterPoolTypeClusterConnection_QNAME = new QName("urn:activemq:core", "cluster-connection");
    private final static QName _ConnectionRouterTypeKeyType_QNAME = new QName("urn:activemq:core", "key-type");
    private final static QName _ConnectionRouterTypeKeyFilter_QNAME = new QName("urn:activemq:core", "key-filter");
    private final static QName _ConnectionRouterTypeLocalTargetFilter_QNAME = new QName("urn:activemq:core", "local-target-filter");
    private final static QName _ConnectionRouterTypeCache_QNAME = new QName("urn:activemq:core", "cache");
    private final static QName _ConnectionRouterTypePolicy_QNAME = new QName("urn:activemq:core", "policy");
    private final static QName _ConnectionRouterTypePool_QNAME = new QName("urn:activemq:core", "pool");
    private final static QName _ConnectionRouterTypeKeyTransformer_QNAME = new QName("urn:activemq:core", "key-transformer");
    private final static QName _AmqpConnectionUriTypeSender_QNAME = new QName("urn:activemq:core", "sender");
    private final static QName _AmqpConnectionUriTypeReceiver_QNAME = new QName("urn:activemq:core", "receiver");
    private final static QName _AmqpConnectionUriTypePeer_QNAME = new QName("urn:activemq:core", "peer");
    private final static QName _AmqpConnectionUriTypeMirror_QNAME = new QName("urn:activemq:core", "mirror");
    private final static QName _AmqpConnectionUriTypeFederation_QNAME = new QName("urn:activemq:core", "federation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.artemis.configuration.jaxb2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SecuritySettings }
     * 
     */
    public SecuritySettings createSecuritySettings() {
        return new SecuritySettings();
    }

    /**
     * Create an instance of {@link BrokerPlugins }
     * 
     */
    public BrokerPlugins createBrokerPlugins() {
        return new BrokerPlugins();
    }

    /**
     * Create an instance of {@link Metrics }
     * 
     */
    public Metrics createMetrics() {
        return new Metrics();
    }

    /**
     * Create an instance of {@link JmsQueueType }
     * 
     */
    public JmsQueueType createJmsQueueType() {
        return new JmsQueueType();
    }

    /**
     * Create an instance of {@link ScaleDownType }
     * 
     */
    public ScaleDownType createScaleDownType() {
        return new ScaleDownType();
    }

    /**
     * Create an instance of {@link HaColocationReplicationType }
     * 
     */
    public HaColocationReplicationType createHaColocationReplicationType() {
        return new HaColocationReplicationType();
    }

    /**
     * Create an instance of {@link DistributedPrimitiveManager }
     * 
     */
    public DistributedPrimitiveManager createDistributedPrimitiveManager() {
        return new DistributedPrimitiveManager();
    }

    /**
     * Create an instance of {@link DatabaseStoreType }
     * 
     */
    public DatabaseStoreType createDatabaseStoreType() {
        return new DatabaseStoreType();
    }

    /**
     * Create an instance of {@link ConnectionRouterPoolType }
     * 
     */
    public ConnectionRouterPoolType createConnectionRouterPoolType() {
        return new ConnectionRouterPoolType();
    }

    /**
     * Create an instance of {@link StreamType }
     * 
     */
    public StreamType createStreamType() {
        return new StreamType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link SecuritySettings.SecuritySettingPlugin }
     * 
     */
    public SecuritySettings.SecuritySettingPlugin createSecuritySettingsSecuritySettingPlugin() {
        return new SecuritySettings.SecuritySettingPlugin();
    }

    /**
     * Create an instance of {@link SecuritySettings.SecuritySetting }
     * 
     */
    public SecuritySettings.SecuritySetting createSecuritySettingsSecuritySetting() {
        return new SecuritySettings.SecuritySetting();
    }

    /**
     * Create an instance of {@link ConfigurationType }
     * 
     */
    public ConfigurationType createConfigurationType() {
        return new ConfigurationType();
    }

    /**
     * Create an instance of {@link ConfigurationType.Queues }
     * 
     */
    public ConfigurationType.Queues createConfigurationTypeQueues() {
        return new ConfigurationType.Queues();
    }

    /**
     * Create an instance of {@link org.artemis.configuration.jaxb2.StaticConnectors }
     * 
     */
    public org.artemis.configuration.jaxb2.StaticConnectors createStaticConnectors() {
        return new org.artemis.configuration.jaxb2.StaticConnectors();
    }

    /**
     * Create an instance of {@link org.artemis.configuration.jaxb2.DiscoveryGroupRef }
     * 
     */
    public org.artemis.configuration.jaxb2.DiscoveryGroupRef createDiscoveryGroupRef() {
        return new org.artemis.configuration.jaxb2.DiscoveryGroupRef();
    }

    /**
     * Create an instance of {@link BroadcastGroups }
     * 
     */
    public BroadcastGroups createBroadcastGroups() {
        return new BroadcastGroups();
    }

    /**
     * Create an instance of {@link BroadcastGroupType }
     * 
     */
    public BroadcastGroupType createBroadcastGroupType() {
        return new BroadcastGroupType();
    }

    /**
     * Create an instance of {@link DiscoveryGroups }
     * 
     */
    public DiscoveryGroups createDiscoveryGroups() {
        return new DiscoveryGroups();
    }

    /**
     * Create an instance of {@link DiscoveryGroupType }
     * 
     */
    public DiscoveryGroupType createDiscoveryGroupType() {
        return new DiscoveryGroupType();
    }

    /**
     * Create an instance of {@link Bridges }
     * 
     */
    public Bridges createBridges() {
        return new Bridges();
    }

    /**
     * Create an instance of {@link BridgeType }
     * 
     */
    public BridgeType createBridgeType() {
        return new BridgeType();
    }

    /**
     * Create an instance of {@link Federations }
     * 
     */
    public Federations createFederations() {
        return new Federations();
    }

    /**
     * Create an instance of {@link FederationType }
     * 
     */
    public FederationType createFederationType() {
        return new FederationType();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link ClusterConnections }
     * 
     */
    public ClusterConnections createClusterConnections() {
        return new ClusterConnections();
    }

    /**
     * Create an instance of {@link ClusterConnectionUriType2 }
     * 
     */
    public ClusterConnectionUriType2 createClusterConnectionUriType2() {
        return new ClusterConnectionUriType2();
    }

    /**
     * Create an instance of {@link ClusterConnectionType }
     * 
     */
    public ClusterConnectionType createClusterConnectionType() {
        return new ClusterConnectionType();
    }

    /**
     * Create an instance of {@link BrokerConnections }
     * 
     */
    public BrokerConnections createBrokerConnections() {
        return new BrokerConnections();
    }

    /**
     * Create an instance of {@link AmqpConnectionUriType }
     * 
     */
    public AmqpConnectionUriType createAmqpConnectionUriType() {
        return new AmqpConnectionUriType();
    }

    /**
     * Create an instance of {@link ConnectionRouters }
     * 
     */
    public ConnectionRouters createConnectionRouters() {
        return new ConnectionRouters();
    }

    /**
     * Create an instance of {@link ConnectionRouterType }
     * 
     */
    public ConnectionRouterType createConnectionRouterType() {
        return new ConnectionRouterType();
    }

    /**
     * Create an instance of {@link Diverts }
     * 
     */
    public Diverts createDiverts() {
        return new Diverts();
    }

    /**
     * Create an instance of {@link DivertType }
     * 
     */
    public DivertType createDivertType() {
        return new DivertType();
    }

    /**
     * Create an instance of {@link StoreType }
     * 
     */
    public StoreType createStoreType() {
        return new StoreType();
    }

    /**
     * Create an instance of {@link HaPolicy }
     * 
     */
    public HaPolicy createHaPolicy() {
        return new HaPolicy();
    }

    /**
     * Create an instance of {@link HaLiveOnlyPolicyType }
     * 
     */
    public HaLiveOnlyPolicyType createHaLiveOnlyPolicyType() {
        return new HaLiveOnlyPolicyType();
    }

    /**
     * Create an instance of {@link HaPrimaryOnlyPolicyType }
     * 
     */
    public HaPrimaryOnlyPolicyType createHaPrimaryOnlyPolicyType() {
        return new HaPrimaryOnlyPolicyType();
    }

    /**
     * Create an instance of {@link HaReplicationType }
     * 
     */
    public HaReplicationType createHaReplicationType() {
        return new HaReplicationType();
    }

    /**
     * Create an instance of {@link HaSharedStoreType }
     * 
     */
    public HaSharedStoreType createHaSharedStoreType() {
        return new HaSharedStoreType();
    }

    /**
     * Create an instance of {@link GroupingHandlerType }
     * 
     */
    public GroupingHandlerType createGroupingHandlerType() {
        return new GroupingHandlerType();
    }

    /**
     * Create an instance of {@link AddressSettings }
     * 
     */
    public AddressSettings createAddressSettings() {
        return new AddressSettings();
    }

    /**
     * Create an instance of {@link AddressSettingType }
     * 
     */
    public AddressSettingType createAddressSettingType() {
        return new AddressSettingType();
    }

    /**
     * Create an instance of {@link ResourceLimitSettings }
     * 
     */
    public ResourceLimitSettings createResourceLimitSettings() {
        return new ResourceLimitSettings();
    }

    /**
     * Create an instance of {@link ResourceLimitSettingType }
     * 
     */
    public ResourceLimitSettingType createResourceLimitSettingType() {
        return new ResourceLimitSettingType();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link ConnectorServices }
     * 
     */
    public ConnectorServices createConnectorServices() {
        return new ConnectorServices();
    }

    /**
     * Create an instance of {@link ConnectorServiceType }
     * 
     */
    public ConnectorServiceType createConnectorServiceType() {
        return new ConnectorServiceType();
    }

    /**
     * Create an instance of {@link org.artemis.configuration.jaxb2.Connectors }
     * 
     */
    public org.artemis.configuration.jaxb2.Connectors createConnectors() {
        return new org.artemis.configuration.jaxb2.Connectors();
    }

    /**
     * Create an instance of {@link TransportType }
     * 
     */
    public TransportType createTransportType() {
        return new TransportType();
    }

    /**
     * Create an instance of {@link Acceptors }
     * 
     */
    public Acceptors createAcceptors() {
        return new Acceptors();
    }

    /**
     * Create an instance of {@link SecuritySettings.RoleMapping }
     * 
     */
    public SecuritySettings.RoleMapping createSecuritySettingsRoleMapping() {
        return new SecuritySettings.RoleMapping();
    }

    /**
     * Create an instance of {@link BrokerPlugins.BrokerPlugin }
     * 
     */
    public BrokerPlugins.BrokerPlugin createBrokerPluginsBrokerPlugin() {
        return new BrokerPlugins.BrokerPlugin();
    }

    /**
     * Create an instance of {@link Metrics.Plugin }
     * 
     */
    public Metrics.Plugin createMetricsPlugin() {
        return new Metrics.Plugin();
    }

    /**
     * Create an instance of {@link Addresses }
     * 
     */
    public Addresses createAddresses() {
        return new Addresses();
    }

    /**
     * Create an instance of {@link WildcardAddresses }
     * 
     */
    public WildcardAddresses createWildcardAddresses() {
        return new WildcardAddresses();
    }

    /**
     * Create an instance of {@link ClassNameSequenceType }
     * 
     */
    public ClassNameSequenceType createClassNameSequenceType() {
        return new ClassNameSequenceType();
    }

    /**
     * Create an instance of {@link ParamType }
     * 
     */
    public ParamType createParamType() {
        return new ParamType();
    }

    /**
     * Create an instance of {@link DownstreamType }
     * 
     */
    public DownstreamType createDownstreamType() {
        return new DownstreamType();
    }

    /**
     * Create an instance of {@link UpstreamType }
     * 
     */
    public UpstreamType createUpstreamType() {
        return new UpstreamType();
    }

    /**
     * Create an instance of {@link PolicySetType }
     * 
     */
    public PolicySetType createPolicySetType() {
        return new PolicySetType();
    }

    /**
     * Create an instance of {@link PolicyRefType }
     * 
     */
    public PolicyRefType createPolicyRefType() {
        return new PolicyRefType();
    }

    /**
     * Create an instance of {@link QueuePolicyType }
     * 
     */
    public QueuePolicyType createQueuePolicyType() {
        return new QueuePolicyType();
    }

    /**
     * Create an instance of {@link QueueMatchType }
     * 
     */
    public QueueMatchType createQueueMatchType() {
        return new QueueMatchType();
    }

    /**
     * Create an instance of {@link AddressPolicyType }
     * 
     */
    public AddressPolicyType createAddressPolicyType() {
        return new AddressPolicyType();
    }

    /**
     * Create an instance of {@link AddressMatchType }
     * 
     */
    public AddressMatchType createAddressMatchType() {
        return new AddressMatchType();
    }

    /**
     * Create an instance of {@link FederationTransformerType }
     * 
     */
    public FederationTransformerType createFederationTransformerType() {
        return new FederationTransformerType();
    }

    /**
     * Create an instance of {@link TransformerType }
     * 
     */
    public TransformerType createTransformerType() {
        return new TransformerType();
    }

    /**
     * Create an instance of {@link ConnectionRouterCacheType }
     * 
     */
    public ConnectionRouterCacheType createConnectionRouterCacheType() {
        return new ConnectionRouterCacheType();
    }

    /**
     * Create an instance of {@link ConnectionRouterPolicyType }
     * 
     */
    public ConnectionRouterPolicyType createConnectionRouterPolicyType() {
        return new ConnectionRouterPolicyType();
    }

    /**
     * Create an instance of {@link ConnectionRouterKeyTransformerType }
     * 
     */
    public ConnectionRouterKeyTransformerType createConnectionRouterKeyTransformerType() {
        return new ConnectionRouterKeyTransformerType();
    }

    /**
     * Create an instance of {@link AmqpAddressMatchType }
     * 
     */
    public AmqpAddressMatchType createAmqpAddressMatchType() {
        return new AmqpAddressMatchType();
    }

    /**
     * Create an instance of {@link AmqpMirrorType }
     * 
     */
    public AmqpMirrorType createAmqpMirrorType() {
        return new AmqpMirrorType();
    }

    /**
     * Create an instance of {@link AmqpFederationType }
     * 
     */
    public AmqpFederationType createAmqpFederationType() {
        return new AmqpFederationType();
    }

    /**
     * Create an instance of {@link AmqpFederationQueuePolicyType }
     * 
     */
    public AmqpFederationQueuePolicyType createAmqpFederationQueuePolicyType() {
        return new AmqpFederationQueuePolicyType();
    }

    /**
     * Create an instance of {@link AmqpFederationAddressPolicyType }
     * 
     */
    public AmqpFederationAddressPolicyType createAmqpFederationAddressPolicyType() {
        return new AmqpFederationAddressPolicyType();
    }

    /**
     * Create an instance of {@link ClusterConnectionUriType }
     * 
     */
    public ClusterConnectionUriType createClusterConnectionUriType() {
        return new ClusterConnectionUriType();
    }

    /**
     * Create an instance of {@link FileStoreType }
     * 
     */
    public FileStoreType createFileStoreType() {
        return new FileStoreType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link HaColocationSharedStoreType }
     * 
     */
    public HaColocationSharedStoreType createHaColocationSharedStoreType() {
        return new HaColocationSharedStoreType();
    }

    /**
     * Create an instance of {@link ReplicationPrimaryPolicyType }
     * 
     */
    public ReplicationPrimaryPolicyType createReplicationPrimaryPolicyType() {
        return new ReplicationPrimaryPolicyType();
    }

    /**
     * Create an instance of {@link ReplicationBackupPolicyType }
     * 
     */
    public ReplicationBackupPolicyType createReplicationBackupPolicyType() {
        return new ReplicationBackupPolicyType();
    }

    /**
     * Create an instance of {@link ColocatedReplicaPolicyType }
     * 
     */
    public ColocatedReplicaPolicyType createColocatedReplicaPolicyType() {
        return new ColocatedReplicaPolicyType();
    }

    /**
     * Create an instance of {@link SharedStorePrimaryPolicyType }
     * 
     */
    public SharedStorePrimaryPolicyType createSharedStorePrimaryPolicyType() {
        return new SharedStorePrimaryPolicyType();
    }

    /**
     * Create an instance of {@link SharedStoreBackupPolicyType }
     * 
     */
    public SharedStoreBackupPolicyType createSharedStoreBackupPolicyType() {
        return new SharedStoreBackupPolicyType();
    }

    /**
     * Create an instance of {@link ColocatedPolicyType }
     * 
     */
    public ColocatedPolicyType createColocatedPolicyType() {
        return new ColocatedPolicyType();
    }

    /**
     * Create an instance of {@link QueueType }
     * 
     */
    public QueueType createQueueType() {
        return new QueueType();
    }

    /**
     * Create an instance of {@link Jms }
     * 
     */
    public Jms createJms() {
        return new Jms();
    }

    /**
     * Create an instance of {@link TopicType }
     * 
     */
    public TopicType createTopicType() {
        return new TopicType();
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link JmsQueueType.Selector }
     * 
     */
    public JmsQueueType.Selector createJmsQueueTypeSelector() {
        return new JmsQueueType.Selector();
    }

    /**
     * Create an instance of {@link ScaleDownType.DiscoveryGroupRef }
     * 
     */
    public ScaleDownType.DiscoveryGroupRef createScaleDownTypeDiscoveryGroupRef() {
        return new ScaleDownType.DiscoveryGroupRef();
    }

    /**
     * Create an instance of {@link ScaleDownType.Connectors }
     * 
     */
    public ScaleDownType.Connectors createScaleDownTypeConnectors() {
        return new ScaleDownType.Connectors();
    }

    /**
     * Create an instance of {@link HaColocationReplicationType.Excludes }
     * 
     */
    public HaColocationReplicationType.Excludes createHaColocationReplicationTypeExcludes() {
        return new HaColocationReplicationType.Excludes();
    }

    /**
     * Create an instance of {@link DistributedPrimitiveManager.Properties }
     * 
     */
    public DistributedPrimitiveManager.Properties createDistributedPrimitiveManagerProperties() {
        return new DistributedPrimitiveManager.Properties();
    }

    /**
     * Create an instance of {@link DatabaseStoreType.DataSourceProperties }
     * 
     */
    public DatabaseStoreType.DataSourceProperties createDatabaseStoreTypeDataSourceProperties() {
        return new DatabaseStoreType.DataSourceProperties();
    }

    /**
     * Create an instance of {@link ConnectionRouterPoolType.StaticConnectors }
     * 
     */
    public ConnectionRouterPoolType.StaticConnectors createConnectionRouterPoolTypeStaticConnectors() {
        return new ConnectionRouterPoolType.StaticConnectors();
    }

    /**
     * Create an instance of {@link ConnectionRouterPoolType.DiscoveryGroupRef }
     * 
     */
    public ConnectionRouterPoolType.DiscoveryGroupRef createConnectionRouterPoolTypeDiscoveryGroupRef() {
        return new ConnectionRouterPoolType.DiscoveryGroupRef();
    }

    /**
     * Create an instance of {@link StreamType.StaticConnectors }
     * 
     */
    public StreamType.StaticConnectors createStreamTypeStaticConnectors() {
        return new StreamType.StaticConnectors();
    }

    /**
     * Create an instance of {@link StreamType.DiscoveryGroupRef }
     * 
     */
    public StreamType.DiscoveryGroupRef createStreamTypeDiscoveryGroupRef() {
        return new StreamType.DiscoveryGroupRef();
    }

    /**
     * Create an instance of {@link AddressType.Anycast }
     * 
     */
    public AddressType.Anycast createAddressTypeAnycast() {
        return new AddressType.Anycast();
    }

    /**
     * Create an instance of {@link AddressType.Multicast }
     * 
     */
    public AddressType.Multicast createAddressTypeMulticast() {
        return new AddressType.Multicast();
    }

    /**
     * Create an instance of {@link SecuritySettings.SecuritySettingPlugin.Setting }
     * 
     */
    public SecuritySettings.SecuritySettingPlugin.Setting createSecuritySettingsSecuritySettingPluginSetting() {
        return new SecuritySettings.SecuritySettingPlugin.Setting();
    }

    /**
     * Create an instance of {@link SecuritySettings.SecuritySetting.Permission }
     * 
     */
    public SecuritySettings.SecuritySetting.Permission createSecuritySettingsSecuritySettingPermission() {
        return new SecuritySettings.SecuritySetting.Permission();
    }

    /**
     * Create an instance of {@link ConfigurationType.JournalRetentionDirectory }
     * 
     */
    public ConfigurationType.JournalRetentionDirectory createConfigurationTypeJournalRetentionDirectory() {
        return new ConfigurationType.JournalRetentionDirectory();
    }

    /**
     * Create an instance of {@link ConfigurationType.MetricsPlugin }
     * 
     */
    public ConfigurationType.MetricsPlugin createConfigurationTypeMetricsPlugin() {
        return new ConfigurationType.MetricsPlugin();
    }

    /**
     * Create an instance of {@link ConfigurationType.Queues.Queue }
     * 
     */
    public ConfigurationType.Queues.Queue createConfigurationTypeQueuesQueue() {
        return new ConfigurationType.Queues.Queue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigurationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ConfigurationType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "core")
    public JAXBElement<ConfigurationType> createCore(ConfigurationType value) {
        return new JAXBElement<ConfigurationType>(_Core_QNAME, ConfigurationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "local-bind-address")
    public JAXBElement<String> createLocalBindAddress(String value) {
        return new JAXBElement<String>(_LocalBindAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "local-bind-port", defaultValue = "-1")
    public JAXBElement<Integer> createLocalBindPort(Integer value) {
        return new JAXBElement<Integer>(_LocalBindPort_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "discovery-type")
    public JAXBElement<Object> createDiscoveryType(Object value) {
        return new JAXBElement<Object>(_DiscoveryType_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link org.artemis.configuration.jaxb2.StaticConnectors }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link org.artemis.configuration.jaxb2.StaticConnectors }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "static-connectors", substitutionHeadNamespace = "urn:activemq:core", substitutionHeadName = "discovery-type")
    public JAXBElement<org.artemis.configuration.jaxb2.StaticConnectors> createStaticConnectors(org.artemis.configuration.jaxb2.StaticConnectors value) {
        return new JAXBElement<org.artemis.configuration.jaxb2.StaticConnectors>(_StaticConnectors_QNAME, org.artemis.configuration.jaxb2.StaticConnectors.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link org.artemis.configuration.jaxb2.DiscoveryGroupRef }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link org.artemis.configuration.jaxb2.DiscoveryGroupRef }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "discovery-group-ref", substitutionHeadNamespace = "urn:activemq:core", substitutionHeadName = "discovery-type")
    public JAXBElement<org.artemis.configuration.jaxb2.DiscoveryGroupRef> createDiscoveryGroupRef(org.artemis.configuration.jaxb2.DiscoveryGroupRef value) {
        return new JAXBElement<org.artemis.configuration.jaxb2.DiscoveryGroupRef>(_DiscoveryGroupRef_QNAME, org.artemis.configuration.jaxb2.DiscoveryGroupRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StoreType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StoreType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "store")
    public JAXBElement<StoreType> createStore(StoreType value) {
        return new JAXBElement<StoreType>(_Store_QNAME, StoreType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupingHandlerType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GroupingHandlerType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "grouping-handler")
    public JAXBElement<GroupingHandlerType> createGroupingHandler(GroupingHandlerType value) {
        return new JAXBElement<GroupingHandlerType>(_GroupingHandler_QNAME, GroupingHandlerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JmsQueueType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link JmsQueueType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:jms", name = "queue")
    public JAXBElement<JmsQueueType> createQueue(JmsQueueType value) {
        return new JAXBElement<JmsQueueType>(_Queue_QNAME, JmsQueueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TopicType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TopicType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:jms", name = "topic")
    public JAXBElement<TopicType> createTopic(TopicType value) {
        return new JAXBElement<TopicType>(_Topic_QNAME, TopicType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmqpFederationQueuePolicyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AmqpFederationQueuePolicyType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "local-queue-policy", scope = AmqpFederationType.class)
    public JAXBElement<AmqpFederationQueuePolicyType> createAmqpFederationTypeLocalQueuePolicy(AmqpFederationQueuePolicyType value) {
        return new JAXBElement<AmqpFederationQueuePolicyType>(_AmqpFederationTypeLocalQueuePolicy_QNAME, AmqpFederationQueuePolicyType.class, AmqpFederationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmqpFederationAddressPolicyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AmqpFederationAddressPolicyType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "local-address-policy", scope = AmqpFederationType.class)
    public JAXBElement<AmqpFederationAddressPolicyType> createAmqpFederationTypeLocalAddressPolicy(AmqpFederationAddressPolicyType value) {
        return new JAXBElement<AmqpFederationAddressPolicyType>(_AmqpFederationTypeLocalAddressPolicy_QNAME, AmqpFederationAddressPolicyType.class, AmqpFederationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmqpFederationQueuePolicyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AmqpFederationQueuePolicyType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "remote-queue-policy", scope = AmqpFederationType.class)
    public JAXBElement<AmqpFederationQueuePolicyType> createAmqpFederationTypeRemoteQueuePolicy(AmqpFederationQueuePolicyType value) {
        return new JAXBElement<AmqpFederationQueuePolicyType>(_AmqpFederationTypeRemoteQueuePolicy_QNAME, AmqpFederationQueuePolicyType.class, AmqpFederationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmqpFederationAddressPolicyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AmqpFederationAddressPolicyType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "remote-address-policy", scope = AmqpFederationType.class)
    public JAXBElement<AmqpFederationAddressPolicyType> createAmqpFederationTypeRemoteAddressPolicy(AmqpFederationAddressPolicyType value) {
        return new JAXBElement<AmqpFederationAddressPolicyType>(_AmqpFederationTypeRemoteAddressPolicy_QNAME, AmqpFederationAddressPolicyType.class, AmqpFederationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "username", scope = ConnectionRouterPoolType.class)
    public JAXBElement<String> createConnectionRouterPoolTypeUsername(String value) {
        return new JAXBElement<String>(_ConnectionRouterPoolTypeUsername_QNAME, String.class, ConnectionRouterPoolType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "password", scope = ConnectionRouterPoolType.class)
    public JAXBElement<String> createConnectionRouterPoolTypePassword(String value) {
        return new JAXBElement<String>(_ConnectionRouterPoolTypePassword_QNAME, String.class, ConnectionRouterPoolType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "check-period", scope = ConnectionRouterPoolType.class, defaultValue = "5000")
    public JAXBElement<Long> createConnectionRouterPoolTypeCheckPeriod(Long value) {
        return new JAXBElement<Long>(_ConnectionRouterPoolTypeCheckPeriod_QNAME, Long.class, ConnectionRouterPoolType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "quorum-size", scope = ConnectionRouterPoolType.class, defaultValue = "1")
    public JAXBElement<Long> createConnectionRouterPoolTypeQuorumSize(Long value) {
        return new JAXBElement<Long>(_ConnectionRouterPoolTypeQuorumSize_QNAME, Long.class, ConnectionRouterPoolType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "quorum-timeout", scope = ConnectionRouterPoolType.class, defaultValue = "3000")
    public JAXBElement<Long> createConnectionRouterPoolTypeQuorumTimeout(Long value) {
        return new JAXBElement<Long>(_ConnectionRouterPoolTypeQuorumTimeout_QNAME, Long.class, ConnectionRouterPoolType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "local-target-enabled", scope = ConnectionRouterPoolType.class, defaultValue = "false")
    public JAXBElement<Boolean> createConnectionRouterPoolTypeLocalTargetEnabled(Boolean value) {
        return new JAXBElement<Boolean>(_ConnectionRouterPoolTypeLocalTargetEnabled_QNAME, Boolean.class, ConnectionRouterPoolType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "cluster-connection", scope = ConnectionRouterPoolType.class)
    public JAXBElement<String> createConnectionRouterPoolTypeClusterConnection(String value) {
        return new JAXBElement<String>(_ConnectionRouterPoolTypeClusterConnection_QNAME, String.class, ConnectionRouterPoolType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectionRouterPoolType.StaticConnectors }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ConnectionRouterPoolType.StaticConnectors }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "static-connectors", scope = ConnectionRouterPoolType.class)
    public JAXBElement<ConnectionRouterPoolType.StaticConnectors> createConnectionRouterPoolTypeStaticConnectors(ConnectionRouterPoolType.StaticConnectors value) {
        return new JAXBElement<ConnectionRouterPoolType.StaticConnectors>(_StaticConnectors_QNAME, ConnectionRouterPoolType.StaticConnectors.class, ConnectionRouterPoolType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectionRouterPoolType.DiscoveryGroupRef }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ConnectionRouterPoolType.DiscoveryGroupRef }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "discovery-group-ref", scope = ConnectionRouterPoolType.class)
    public JAXBElement<ConnectionRouterPoolType.DiscoveryGroupRef> createConnectionRouterPoolTypeDiscoveryGroupRef(ConnectionRouterPoolType.DiscoveryGroupRef value) {
        return new JAXBElement<ConnectionRouterPoolType.DiscoveryGroupRef>(_DiscoveryGroupRef_QNAME, ConnectionRouterPoolType.DiscoveryGroupRef.class, ConnectionRouterPoolType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectionRouterKeyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ConnectionRouterKeyType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "key-type", scope = ConnectionRouterType.class)
    public JAXBElement<ConnectionRouterKeyType> createConnectionRouterTypeKeyType(ConnectionRouterKeyType value) {
        return new JAXBElement<ConnectionRouterKeyType>(_ConnectionRouterTypeKeyType_QNAME, ConnectionRouterKeyType.class, ConnectionRouterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "key-filter", scope = ConnectionRouterType.class)
    public JAXBElement<String> createConnectionRouterTypeKeyFilter(String value) {
        return new JAXBElement<String>(_ConnectionRouterTypeKeyFilter_QNAME, String.class, ConnectionRouterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "local-target-filter", scope = ConnectionRouterType.class)
    public JAXBElement<String> createConnectionRouterTypeLocalTargetFilter(String value) {
        return new JAXBElement<String>(_ConnectionRouterTypeLocalTargetFilter_QNAME, String.class, ConnectionRouterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectionRouterCacheType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ConnectionRouterCacheType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "cache", scope = ConnectionRouterType.class)
    public JAXBElement<ConnectionRouterCacheType> createConnectionRouterTypeCache(ConnectionRouterCacheType value) {
        return new JAXBElement<ConnectionRouterCacheType>(_ConnectionRouterTypeCache_QNAME, ConnectionRouterCacheType.class, ConnectionRouterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectionRouterPolicyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ConnectionRouterPolicyType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "policy", scope = ConnectionRouterType.class)
    public JAXBElement<ConnectionRouterPolicyType> createConnectionRouterTypePolicy(ConnectionRouterPolicyType value) {
        return new JAXBElement<ConnectionRouterPolicyType>(_ConnectionRouterTypePolicy_QNAME, ConnectionRouterPolicyType.class, ConnectionRouterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectionRouterPoolType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ConnectionRouterPoolType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "pool", scope = ConnectionRouterType.class)
    public JAXBElement<ConnectionRouterPoolType> createConnectionRouterTypePool(ConnectionRouterPoolType value) {
        return new JAXBElement<ConnectionRouterPoolType>(_ConnectionRouterTypePool_QNAME, ConnectionRouterPoolType.class, ConnectionRouterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectionRouterKeyTransformerType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ConnectionRouterKeyTransformerType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "key-transformer", scope = ConnectionRouterType.class)
    public JAXBElement<ConnectionRouterKeyTransformerType> createConnectionRouterTypeKeyTransformer(ConnectionRouterKeyTransformerType value) {
        return new JAXBElement<ConnectionRouterKeyTransformerType>(_ConnectionRouterTypeKeyTransformer_QNAME, ConnectionRouterKeyTransformerType.class, ConnectionRouterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmqpAddressMatchType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AmqpAddressMatchType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "sender", scope = AmqpConnectionUriType.class)
    public JAXBElement<AmqpAddressMatchType> createAmqpConnectionUriTypeSender(AmqpAddressMatchType value) {
        return new JAXBElement<AmqpAddressMatchType>(_AmqpConnectionUriTypeSender_QNAME, AmqpAddressMatchType.class, AmqpConnectionUriType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmqpAddressMatchType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AmqpAddressMatchType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "receiver", scope = AmqpConnectionUriType.class)
    public JAXBElement<AmqpAddressMatchType> createAmqpConnectionUriTypeReceiver(AmqpAddressMatchType value) {
        return new JAXBElement<AmqpAddressMatchType>(_AmqpConnectionUriTypeReceiver_QNAME, AmqpAddressMatchType.class, AmqpConnectionUriType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmqpAddressMatchType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AmqpAddressMatchType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "peer", scope = AmqpConnectionUriType.class)
    public JAXBElement<AmqpAddressMatchType> createAmqpConnectionUriTypePeer(AmqpAddressMatchType value) {
        return new JAXBElement<AmqpAddressMatchType>(_AmqpConnectionUriTypePeer_QNAME, AmqpAddressMatchType.class, AmqpConnectionUriType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmqpMirrorType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AmqpMirrorType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "mirror", scope = AmqpConnectionUriType.class)
    public JAXBElement<AmqpMirrorType> createAmqpConnectionUriTypeMirror(AmqpMirrorType value) {
        return new JAXBElement<AmqpMirrorType>(_AmqpConnectionUriTypeMirror_QNAME, AmqpMirrorType.class, AmqpConnectionUriType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmqpFederationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AmqpFederationType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:activemq:core", name = "federation", scope = AmqpConnectionUriType.class)
    public JAXBElement<AmqpFederationType> createAmqpConnectionUriTypeFederation(AmqpFederationType value) {
        return new JAXBElement<AmqpFederationType>(_AmqpConnectionUriTypeFederation_QNAME, AmqpFederationType.class, AmqpConnectionUriType.class, value);
    }

}
