//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.07 at 10:08:36 PM CEST 
//


package org.artemis.configuration.jaxb2;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for replicationPrimaryPolicyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="replicationPrimaryPolicyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="group-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cluster-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="max-saved-replicated-journals-size" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="check-for-live-server" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="check-for-active-server" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="initial-replication-sync-timeout" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="vote-on-replication-failure" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="quorum-size" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="vote-retries" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="vote-retry-wait" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="quorum-vote-wait" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="retry-replication-wait" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="manager" type="{urn:activemq:core}distributed-primitive-manager" minOccurs="0"/&gt;
 *         &lt;element name="coordination-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *       &lt;attGroup ref="{http://www.w3.org/XML/1998/namespace}specialAttrs"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "replicationPrimaryPolicyType", propOrder = {

})
public class ReplicationPrimaryPolicyType {

    @XmlElement(name = "group-name")
    protected String groupName;
    @XmlElement(name = "cluster-name")
    protected String clusterName;
    @XmlElement(name = "max-saved-replicated-journals-size", defaultValue = "2")
    protected Integer maxSavedReplicatedJournalsSize;
    @XmlElement(name = "check-for-live-server", defaultValue = "false")
    protected Boolean checkForLiveServer;
    @XmlElement(name = "check-for-active-server", defaultValue = "false")
    protected Boolean checkForActiveServer;
    @XmlElement(name = "initial-replication-sync-timeout", defaultValue = "30000")
    protected Long initialReplicationSyncTimeout;
    @XmlElement(name = "vote-on-replication-failure", defaultValue = "false")
    protected Boolean voteOnReplicationFailure;
    @XmlElement(name = "quorum-size", defaultValue = "-1")
    protected BigInteger quorumSize;
    @XmlElement(name = "vote-retries", defaultValue = "12")
    protected BigInteger voteRetries;
    @XmlElement(name = "vote-retry-wait", defaultValue = "5000")
    protected Long voteRetryWait;
    @XmlElement(name = "quorum-vote-wait", defaultValue = "30")
    protected BigInteger quorumVoteWait;
    @XmlElement(name = "retry-replication-wait", defaultValue = "2000")
    protected Long retryReplicationWait;
    protected DistributedPrimitiveManager manager;
    @XmlElement(name = "coordination-id")
    protected String coordinationId;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

    /**
     * Gets the value of the clusterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClusterName() {
        return clusterName;
    }

    /**
     * Sets the value of the clusterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClusterName(String value) {
        this.clusterName = value;
    }

    /**
     * Gets the value of the maxSavedReplicatedJournalsSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxSavedReplicatedJournalsSize() {
        return maxSavedReplicatedJournalsSize;
    }

    /**
     * Sets the value of the maxSavedReplicatedJournalsSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxSavedReplicatedJournalsSize(Integer value) {
        this.maxSavedReplicatedJournalsSize = value;
    }

    /**
     * Gets the value of the checkForLiveServer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCheckForLiveServer() {
        return checkForLiveServer;
    }

    /**
     * Sets the value of the checkForLiveServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCheckForLiveServer(Boolean value) {
        this.checkForLiveServer = value;
    }

    /**
     * Gets the value of the checkForActiveServer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCheckForActiveServer() {
        return checkForActiveServer;
    }

    /**
     * Sets the value of the checkForActiveServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCheckForActiveServer(Boolean value) {
        this.checkForActiveServer = value;
    }

    /**
     * Gets the value of the initialReplicationSyncTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getInitialReplicationSyncTimeout() {
        return initialReplicationSyncTimeout;
    }

    /**
     * Sets the value of the initialReplicationSyncTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setInitialReplicationSyncTimeout(Long value) {
        this.initialReplicationSyncTimeout = value;
    }

    /**
     * Gets the value of the voteOnReplicationFailure property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVoteOnReplicationFailure() {
        return voteOnReplicationFailure;
    }

    /**
     * Sets the value of the voteOnReplicationFailure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVoteOnReplicationFailure(Boolean value) {
        this.voteOnReplicationFailure = value;
    }

    /**
     * Gets the value of the quorumSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQuorumSize() {
        return quorumSize;
    }

    /**
     * Sets the value of the quorumSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQuorumSize(BigInteger value) {
        this.quorumSize = value;
    }

    /**
     * Gets the value of the voteRetries property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVoteRetries() {
        return voteRetries;
    }

    /**
     * Sets the value of the voteRetries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVoteRetries(BigInteger value) {
        this.voteRetries = value;
    }

    /**
     * Gets the value of the voteRetryWait property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVoteRetryWait() {
        return voteRetryWait;
    }

    /**
     * Sets the value of the voteRetryWait property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVoteRetryWait(Long value) {
        this.voteRetryWait = value;
    }

    /**
     * Gets the value of the quorumVoteWait property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQuorumVoteWait() {
        return quorumVoteWait;
    }

    /**
     * Sets the value of the quorumVoteWait property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQuorumVoteWait(BigInteger value) {
        this.quorumVoteWait = value;
    }

    /**
     * Gets the value of the retryReplicationWait property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRetryReplicationWait() {
        return retryReplicationWait;
    }

    /**
     * Sets the value of the retryReplicationWait property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRetryReplicationWait(Long value) {
        this.retryReplicationWait = value;
    }

    /**
     * Gets the value of the manager property.
     * 
     * @return
     *     possible object is
     *     {@link DistributedPrimitiveManager }
     *     
     */
    public DistributedPrimitiveManager getManager() {
        return manager;
    }

    /**
     * Sets the value of the manager property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributedPrimitiveManager }
     *     
     */
    public void setManager(DistributedPrimitiveManager value) {
        this.manager = value;
    }

    /**
     * Gets the value of the coordinationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordinationId() {
        return coordinationId;
    }

    /**
     * Sets the value of the coordinationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordinationId(String value) {
        this.coordinationId = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

}
