//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.07 at 10:08:36 PM CEST 
//


package org.artemis.configuration.jaxb2;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for streamType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="streamType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ha" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="circuit-breaker-timeout" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="share-connection" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="connection-ttl" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="call-timeout" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="retry-interval" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="retry-interval-multiplier" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="max-retry-interval" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="initial-connect-attempts" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="reconnect-attempts" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="check-period" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="call-failover-timeout" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="static-connectors"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="connector-ref" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;attGroup ref="{http://www.w3.org/XML/1998/namespace}specialAttrs"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="discovery-group-ref"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;attGroup ref="{http://www.w3.org/XML/1998/namespace}specialAttrs"/&gt;
 *                   &lt;attribute name="discovery-group-name" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="policy" type="{urn:activemq:core}policyRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.w3.org/XML/1998/namespace}specialAttrs"/&gt;
 *       &lt;attribute name="priority-adjustment" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="user" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="password" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "streamType", propOrder = {
    "ha",
    "circuitBreakerTimeout",
    "shareConnection",
    "connectionTtl",
    "callTimeout",
    "retryInterval",
    "retryIntervalMultiplier",
    "maxRetryInterval",
    "initialConnectAttempts",
    "reconnectAttempts",
    "checkPeriod",
    "callFailoverTimeout",
    "staticConnectors",
    "discoveryGroupRef",
    "policy"
})
@XmlSeeAlso({
    DownstreamType.class,
    UpstreamType.class
})
public class StreamType {

    @XmlElement(defaultValue = "false")
    protected Boolean ha;
    @XmlElement(name = "circuit-breaker-timeout", defaultValue = "30000")
    protected Long circuitBreakerTimeout;
    @XmlElement(name = "share-connection", defaultValue = "false")
    protected Boolean shareConnection;
    @XmlElement(name = "connection-ttl", defaultValue = "60000")
    protected Long connectionTtl;
    @XmlElement(name = "call-timeout", defaultValue = "30000")
    protected Long callTimeout;
    @XmlElement(name = "retry-interval", defaultValue = "500")
    protected Long retryInterval;
    @XmlElement(name = "retry-interval-multiplier", defaultValue = "1")
    protected Double retryIntervalMultiplier;
    @XmlElement(name = "max-retry-interval", defaultValue = "2000")
    protected Long maxRetryInterval;
    @XmlElement(name = "initial-connect-attempts", defaultValue = "-1")
    protected Integer initialConnectAttempts;
    @XmlElement(name = "reconnect-attempts", defaultValue = "-1")
    protected Integer reconnectAttempts;
    @XmlElement(name = "check-period", defaultValue = "30000")
    protected Long checkPeriod;
    @XmlElement(name = "call-failover-timeout", defaultValue = "-1")
    protected Long callFailoverTimeout;
    @XmlElement(name = "static-connectors")
    protected StreamType.StaticConnectors staticConnectors;
    @XmlElement(name = "discovery-group-ref")
    protected StreamType.DiscoveryGroupRef discoveryGroupRef;
    protected List<PolicyRefType> policy;
    @XmlAttribute(name = "priority-adjustment")
    protected Integer priorityAdjustment;
    @XmlAttribute(name = "user")
    protected String user;
    @XmlAttribute(name = "password")
    protected String password;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String name;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;

    /**
     * Gets the value of the ha property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHa() {
        return ha;
    }

    /**
     * Sets the value of the ha property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHa(Boolean value) {
        this.ha = value;
    }

    /**
     * Gets the value of the circuitBreakerTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCircuitBreakerTimeout() {
        return circuitBreakerTimeout;
    }

    /**
     * Sets the value of the circuitBreakerTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCircuitBreakerTimeout(Long value) {
        this.circuitBreakerTimeout = value;
    }

    /**
     * Gets the value of the shareConnection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShareConnection() {
        return shareConnection;
    }

    /**
     * Sets the value of the shareConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShareConnection(Boolean value) {
        this.shareConnection = value;
    }

    /**
     * Gets the value of the connectionTtl property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getConnectionTtl() {
        return connectionTtl;
    }

    /**
     * Sets the value of the connectionTtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setConnectionTtl(Long value) {
        this.connectionTtl = value;
    }

    /**
     * Gets the value of the callTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCallTimeout() {
        return callTimeout;
    }

    /**
     * Sets the value of the callTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCallTimeout(Long value) {
        this.callTimeout = value;
    }

    /**
     * Gets the value of the retryInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRetryInterval() {
        return retryInterval;
    }

    /**
     * Sets the value of the retryInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRetryInterval(Long value) {
        this.retryInterval = value;
    }

    /**
     * Gets the value of the retryIntervalMultiplier property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRetryIntervalMultiplier() {
        return retryIntervalMultiplier;
    }

    /**
     * Sets the value of the retryIntervalMultiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRetryIntervalMultiplier(Double value) {
        this.retryIntervalMultiplier = value;
    }

    /**
     * Gets the value of the maxRetryInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxRetryInterval() {
        return maxRetryInterval;
    }

    /**
     * Sets the value of the maxRetryInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxRetryInterval(Long value) {
        this.maxRetryInterval = value;
    }

    /**
     * Gets the value of the initialConnectAttempts property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInitialConnectAttempts() {
        return initialConnectAttempts;
    }

    /**
     * Sets the value of the initialConnectAttempts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInitialConnectAttempts(Integer value) {
        this.initialConnectAttempts = value;
    }

    /**
     * Gets the value of the reconnectAttempts property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReconnectAttempts() {
        return reconnectAttempts;
    }

    /**
     * Sets the value of the reconnectAttempts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReconnectAttempts(Integer value) {
        this.reconnectAttempts = value;
    }

    /**
     * Gets the value of the checkPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCheckPeriod() {
        return checkPeriod;
    }

    /**
     * Sets the value of the checkPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCheckPeriod(Long value) {
        this.checkPeriod = value;
    }

    /**
     * Gets the value of the callFailoverTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCallFailoverTimeout() {
        return callFailoverTimeout;
    }

    /**
     * Sets the value of the callFailoverTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCallFailoverTimeout(Long value) {
        this.callFailoverTimeout = value;
    }

    /**
     * Gets the value of the staticConnectors property.
     * 
     * @return
     *     possible object is
     *     {@link StreamType.StaticConnectors }
     *     
     */
    public StreamType.StaticConnectors getStaticConnectors() {
        return staticConnectors;
    }

    /**
     * Sets the value of the staticConnectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreamType.StaticConnectors }
     *     
     */
    public void setStaticConnectors(StreamType.StaticConnectors value) {
        this.staticConnectors = value;
    }

    /**
     * Gets the value of the discoveryGroupRef property.
     * 
     * @return
     *     possible object is
     *     {@link StreamType.DiscoveryGroupRef }
     *     
     */
    public StreamType.DiscoveryGroupRef getDiscoveryGroupRef() {
        return discoveryGroupRef;
    }

    /**
     * Sets the value of the discoveryGroupRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreamType.DiscoveryGroupRef }
     *     
     */
    public void setDiscoveryGroupRef(StreamType.DiscoveryGroupRef value) {
        this.discoveryGroupRef = value;
    }

    /**
     * Gets the value of the policy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the policy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolicy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PolicyRefType }
     * 
     * 
     */
    public List<PolicyRefType> getPolicy() {
        if (policy == null) {
            policy = new ArrayList<PolicyRefType>();
        }
        return this.policy;
    }

    /**
     * Gets the value of the priorityAdjustment property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPriorityAdjustment() {
        return priorityAdjustment;
    }

    /**
     * Sets the value of the priorityAdjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPriorityAdjustment(Integer value) {
        this.priorityAdjustment = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attGroup ref="{http://www.w3.org/XML/1998/namespace}specialAttrs"/&gt;
     *       &lt;attribute name="discovery-group-name" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DiscoveryGroupRef {

        @XmlAttribute(name = "discovery-group-name", required = true)
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Object discoveryGroupName;
        @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
        @XmlSchemaType(name = "anyURI")
        protected String base;
        @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
        protected String lang;
        @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String space;

        /**
         * Gets the value of the discoveryGroupName property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDiscoveryGroupName() {
            return discoveryGroupName;
        }

        /**
         * Sets the value of the discoveryGroupName property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDiscoveryGroupName(Object value) {
            this.discoveryGroupName = value;
        }

        /**
         * Gets the value of the base property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBase() {
            return base;
        }

        /**
         * Sets the value of the base property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBase(String value) {
            this.base = value;
        }

        /**
         * Gets the value of the lang property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLang() {
            return lang;
        }

        /**
         * Sets the value of the lang property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLang(String value) {
            this.lang = value;
        }

        /**
         * Gets the value of the space property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpace() {
            return space;
        }

        /**
         * Sets the value of the space property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpace(String value) {
            this.space = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="connector-ref" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attGroup ref="{http://www.w3.org/XML/1998/namespace}specialAttrs"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "connectorRef"
    })
    public static class StaticConnectors {

        @XmlElement(name = "connector-ref", required = true)
        protected List<String> connectorRef;
        @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
        @XmlSchemaType(name = "anyURI")
        protected String base;
        @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
        protected String lang;
        @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String space;

        /**
         * Gets the value of the connectorRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the connectorRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConnectorRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getConnectorRef() {
            if (connectorRef == null) {
                connectorRef = new ArrayList<String>();
            }
            return this.connectorRef;
        }

        /**
         * Gets the value of the base property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBase() {
            return base;
        }

        /**
         * Sets the value of the base property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBase(String value) {
            this.base = value;
        }

        /**
         * Gets the value of the lang property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLang() {
            return lang;
        }

        /**
         * Sets the value of the lang property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLang(String value) {
            this.lang = value;
        }

        /**
         * Gets the value of the space property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpace() {
            return space;
        }

        /**
         * Sets the value of the space property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpace(String value) {
            this.space = value;
        }

    }

}
